In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
data = pd.read_excel('Fig3-1.xls', header = None)

In [4]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,"U.S. Home Price and Related data, for Figure 3...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,See the book for description of data.,NaN,NaN,NaN,"Update Nominal Home Price Index, Click Additio...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Monthly data from January 1953 for prices, all...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nominal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Real,NaN,Real,NaN,NaN,NaN,NaN,Home,NaN,NaN,Nominal,NaN,NaN,Consumer,NaN,NaN,NaN,NaN
4,NaN,Home,NaN,Building,U.S.,NaN,NaN,NaN,Price,HPI,NaN,Building,NaN,NaN,Price,CPI Annual&,NaN,NaN,NaN
5,NaN,Price,NaN,Cost,Population,NaN,Long Rate,NaN,Index,Source,NaN,Cost,Build Cost,NaN,Index,Quarterly,NaN,NaN,CPI
6,Date,Index,Date,Index,Millions,Long Rate,Source,Date,From fig2.1Revised2011.xls,NaN,Date,Index,Source,Date,NaN,NaN,NaN,Date,Annual
7,1890,100,1890,51.3623,63.056,3.42,Homer,1890,3.5573,Grebler,1890,NaN,Grebler,1890,7.61165,Warren&Pearson,NaN,1890,7.61165
8,1891,88.0118,1891,47.2662,64.361,3.62,Homer,1891,3.20911,Grebler,1891,NaN,Grebler,1891,7.80194,Warren&Pearson,NaN,1891,7.80194
9,1892,95.4217,1892,52.0482,65.666,3.6,Homer,1892,3.26714,Grebler,1892,NaN,Grebler,1892,7.32621,Warren&Pearson,NaN,1892,7.32621
10,1893,92.2974,1893,44.6733,66.97,3.75,Homer,1893,3.40642,Grebler,1893,NaN,Grebler,1893,7.89709,Warren&Pearson,NaN,1893,7.89709
11,1894,123.98,1894,57.2634,68.275,3.7,Homer,1894,3.96932,Grebler,1894,NaN,Grebler,1894,6.85048,Warren&Pearson,NaN,1894,6.85048
12,1895,117.455,1895,61.4703,69.58,3.46,Homer,1895,3.60372,Grebler,1895,NaN,Grebler,1895,6.56505,Warren&Pearson,NaN,1895,6.56505
13,1896,100.303,1896,60.0689,70.885,3.6,Homer,1896,3.12206,Grebler,1896,NaN,Grebler,1896,6.66019,Warren&Pearson,NaN,1896,6.66019
14,1897,106.516,1897,62.3849,72.189,3.4,Homer,1897,3.22072,Grebler,1897,NaN,Grebler,1897,6.4699,Warren&Pearson,NaN,1897,6.4699
15,1898,110.184,1898,61.438,73.494,3.35,Homer,1898,3.42963,Grebler,1898,NaN,Grebler,1898,6.66019,Warren&Pearson,NaN,1898,6.66019
16,1899,103.853,1899,64.0446,74.799,3.1,Homer,1899,3.27875,Grebler,1899,NaN,Grebler,1899,6.75534,Warren&Pearson,NaN,1899,6.75534
17,1900,101.574,1900,49.4206,76.094,3.15,Homer,1900,3.7488,Grebler,1900,NaN,Grebler,1900,7.89709,Warren&Pearson,NaN,1900,7.89709
18,1901,87.3261,1901,51.2523,77.584,3.1,Homer,1901,3.14528,Grebler,1901,NaN,Grebler,1901,7.70679,Warren&Pearson,NaN,1901,7.70679
19,1902,100.474,1902,50.5162,79.163,3.18,Homer,1902,3.70818,Grebler,1902,NaN,Grebler,1902,7.89709,Warren&Pearson,NaN,1902,7.89709
20,1903,93.0749,1903,43.5435,80.632,3.3,Homer,1903,3.76621,Grebler,1903,NaN,Grebler,1903,8.65826,Warren&Pearson,NaN,1903,8.65826
21,1904,101.854,1904,47.0856,82.166,3.4,Homer,1904,3.9403,Grebler,1904,NaN,Grebler,1904,8.27768,Warren&Pearson,NaN,1904,8.27768
22,1905,87.2485,1905,47.111,83.822,3.48,Homer,1905,3.45284,Grebler,1905,NaN,Grebler,1905,8.46793,Warren&Pearson,NaN,1905,8.46793
23,1906,103.525,1906,51.7691,85.45,3.43,Homer,1906,4.09698,Grebler,1906,NaN,Grebler,1906,8.46793,Warren&Pearson,NaN,1906,8.46793
24,1907,109.317,1907,49.5447,87.008,3.67,Homer,1907,4.52061,Grebler,1907,NaN,Grebler,1907,8.84851,Warren&Pearson,NaN,1907,8.84851
25,1908,100.819,1908,50.1257,88.71,3.87,Homer,1908,4.07957,Grebler,1908,NaN,Grebler,1908,8.65826,Warren&Pearson,NaN,1908,8.65826
26,1909,95.3804,1909,44.0717,90.49,3.76,Homer,1909,3.98673,Grebler,1909,NaN,Grebler,1909,8.94367,Warren&Pearson,NaN,1909,8.94367
27,1910,93.1106,1910,37.9818,92.407,3.91,Homer,1910,4.3059,Grebler,1910,NaN,Grebler,1910,9.89517,Warren&Pearson,NaN,1910,9.89517
28,1911,97.5433,1911,42.2976,93.863,3.98,Homer,1911,4.20724,Grebler,1911,NaN,Grebler,1911,9.22909,Warren&Pearson,NaN,1911,9.22909
29,1912,102.365,1912,42.2541,95.335,4.01,Homer,1912,4.36973,Grebler,1912,NaN,Grebler,1912,9.134,Warren&Pearson,NaN,1912,9.134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,2016.71,163.128,NaN,NaN,NaN,NaN,NaN,2016.71,184.059,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.71,241.428,BLS,NaN,NaN,NaN
835,2016.79,162.997,NaN,NaN,NaN,NaN,NaN,2016.79,184.141,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.79,241.729,BLS,NaN,NaN,NaN
836,2016.87,163.448,NaN,NaN,NaN,NaN,NaN,2016.87,184.363,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.87,241.353,BLS,NaN,NaN,NaN
837,2016.96,163.552,NaN,NaN,NaN,NaN,NaN,2016.96,184.541,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.96,241.432,BLS,NaN,NaN,NaN
838,2017.04,162.829,NaN,NaN,NaN,NaN,NaN,2017.04,184.795,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.04,242.839,BLS,NaN,NaN,NaN
839,2017.12,162.649,NaN,NaN,NaN,NaN,NaN,2017.12,185.172,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.12,243.603,BLS,NaN,NaN,NaN
840,2017.21,163.837,NaN,NaN,NaN,NaN,NaN,2017.21,186.676,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.21,243.801,BLS,NaN,NaN,NaN
841,2017.29,165.109,NaN,NaN,NaN,NaN,NaN,2017.29,188.683,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.29,244.524,BLS,NaN,NaN,NaN
842,2017.37,166.718,NaN,NaN,NaN,NaN,NaN,2017.37,190.685,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.37,244.733,BLS,NaN,NaN,NaN
843,2017.46,168.09,NaN,NaN,NaN,NaN,NaN,2017.46,192.428,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.46,244.955,BLS,NaN,NaN,NaN
844,2017.54,169.309,NaN,NaN,NaN,NaN,NaN,2017.54,193.69,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.54,244.786,BLS,NaN,NaN,NaN
845,2017.62,169.542,NaN,NaN,NaN,NaN,NaN,2017.62,194.538,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.62,245.519,BLS,NaN,NaN,NaN
846,2017.71,169.063,NaN,NaN,NaN,NaN,NaN,2017.71,195.015,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.71,246.819,BLS,NaN,NaN,NaN
847,2017.79,169.401,NaN,NaN,NaN,NaN,NaN,2017.79,195.282,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.79,246.663,BLS,NaN,NaN,NaN
848,2017.87,169.714,NaN,NaN,NaN,NaN,NaN,2017.87,195.647,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.87,246.669,BLS,NaN,NaN,NaN
849,2017.96,170.17,NaN,NaN,NaN,NaN,NaN,2017.96,196.058,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.96,246.524,BLS,NaN,NaN,NaN
850,2018.04,169.496,NaN,NaN,NaN,NaN,NaN,2018.04,196.345,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.04,247.867,BLS,NaN,NaN,NaN
851,2018.12,169.425,NaN,NaN,NaN,NaN,NaN,2018.12,197.152,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.12,248.991,BLS,NaN,NaN,NaN
852,2018.21,170.486,NaN,NaN,NaN,NaN,NaN,2018.21,198.836,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.21,249.554,BLS,NaN,NaN,NaN
853,2018.29,171.564,NaN,NaN,NaN,NaN,NaN,2018.29,200.888,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.29,250.546,BLS,NaN,NaN,NaN
854,2018.37,172.432,NaN,NaN,NaN,NaN,NaN,2018.37,202.745,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.37,251.588,BLS,NaN,NaN,NaN
855,2018.46,173.518,NaN,NaN,NaN,NaN,NaN,2018.46,204.347,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.46,251.989,BLS,NaN,NaN,NaN
856,2018.54,174.292,NaN,NaN,NaN,NaN,NaN,2018.54,205.272,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.54,252.006,BLS,NaN,NaN,NaN
857,2018.62,174.514,NaN,NaN,NaN,NaN,NaN,2018.62,205.647,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.62,252.146,BLS,NaN,NaN,NaN
858,2018.71,174.362,NaN,NaN,NaN,NaN,NaN,2018.71,205.707,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.71,252.439,BLS,NaN,NaN,NaN
859,2018.79,174.056,NaN,NaN,NaN,NaN,NaN,2018.79,205.709,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.79,252.885,BLS,NaN,NaN,NaN
860,2018.87,174.439,NaN,NaN,NaN,NaN,NaN,2018.87,205.471,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.87,252.038,BLS,NaN,NaN,NaN
861,2018.96,174.659,NaN,NaN,NaN,NaN,NaN,2018.96,205.073,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.96,251.233,BLS,NaN,NaN,NaN
862,2019.04,174.016,NaN,NaN,NaN,NaN,NaN,2019.04,204.708,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2019.04,251.712,BLS,NaN,NaN,NaN
863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.12,252.776,BLS,NaN,NaN,NaN

In [5]:
len(data)

864

In [6]:
data_file = pd.ExcelFile('Fig3-1.xls')  
data = pd.read_excel(data_file, header=None)
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,"U.S. Home Price and Related data, for Figure 3...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,See the book for description of data.,NaN,NaN,NaN,"Update Nominal Home Price Index, Click Additio...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Monthly data from January 1953 for prices, all...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nominal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Real,NaN,Real,NaN,NaN,NaN,NaN,Home,NaN,NaN,Nominal,NaN,NaN,Consumer,NaN,NaN,NaN,NaN
4,NaN,Home,NaN,Building,U.S.,NaN,NaN,NaN,Price,HPI,NaN,Building,NaN,NaN,Price,CPI Annual&,NaN,NaN,NaN
5,NaN,Price,NaN,Cost,Population,NaN,Long Rate,NaN,Index,Source,NaN,Cost,Build Cost,NaN,Index,Quarterly,NaN,NaN,CPI
6,Date,Index,Date,Index,Millions,Long Rate,Source,Date,From fig2.1Revised2011.xls,NaN,Date,Index,Source,Date,NaN,NaN,NaN,Date,Annual
7,1890,100,1890,51.3623,63.056,3.42,Homer,1890,3.5573,Grebler,1890,NaN,Grebler,1890,7.61165,Warren&Pearson,NaN,1890,7.61165
8,1891,88.0118,1891,47.2662,64.361,3.62,Homer,1891,3.20911,Grebler,1891,NaN,Grebler,1891,7.80194,Warren&Pearson,NaN,1891,7.80194
9,1892,95.4217,1892,52.0482,65.666,3.6,Homer,1892,3.26714,Grebler,1892,NaN,Grebler,1892,7.32621,Warren&Pearson,NaN,1892,7.32621
10,1893,92.2974,1893,44.6733,66.97,3.75,Homer,1893,3.40642,Grebler,1893,NaN,Grebler,1893,7.89709,Warren&Pearson,NaN,1893,7.89709
11,1894,123.98,1894,57.2634,68.275,3.7,Homer,1894,3.96932,Grebler,1894,NaN,Grebler,1894,6.85048,Warren&Pearson,NaN,1894,6.85048
12,1895,117.455,1895,61.4703,69.58,3.46,Homer,1895,3.60372,Grebler,1895,NaN,Grebler,1895,6.56505,Warren&Pearson,NaN,1895,6.56505
13,1896,100.303,1896,60.0689,70.885,3.6,Homer,1896,3.12206,Grebler,1896,NaN,Grebler,1896,6.66019,Warren&Pearson,NaN,1896,6.66019
14,1897,106.516,1897,62.3849,72.189,3.4,Homer,1897,3.22072,Grebler,1897,NaN,Grebler,1897,6.4699,Warren&Pearson,NaN,1897,6.4699
15,1898,110.184,1898,61.438,73.494,3.35,Homer,1898,3.42963,Grebler,1898,NaN,Grebler,1898,6.66019,Warren&Pearson,NaN,1898,6.66019
16,1899,103.853,1899,64.0446,74.799,3.1,Homer,1899,3.27875,Grebler,1899,NaN,Grebler,1899,6.75534,Warren&Pearson,NaN,1899,6.75534
17,1900,101.574,1900,49.4206,76.094,3.15,Homer,1900,3.7488,Grebler,1900,NaN,Grebler,1900,7.89709,Warren&Pearson,NaN,1900,7.89709
18,1901,87.3261,1901,51.2523,77.584,3.1,Homer,1901,3.14528,Grebler,1901,NaN,Grebler,1901,7.70679,Warren&Pearson,NaN,1901,7.70679
19,1902,100.474,1902,50.5162,79.163,3.18,Homer,1902,3.70818,Grebler,1902,NaN,Grebler,1902,7.89709,Warren&Pearson,NaN,1902,7.89709
20,1903,93.0749,1903,43.5435,80.632,3.3,Homer,1903,3.76621,Grebler,1903,NaN,Grebler,1903,8.65826,Warren&Pearson,NaN,1903,8.65826
21,1904,101.854,1904,47.0856,82.166,3.4,Homer,1904,3.9403,Grebler,1904,NaN,Grebler,1904,8.27768,Warren&Pearson,NaN,1904,8.27768
22,1905,87.2485,1905,47.111,83.822,3.48,Homer,1905,3.45284,Grebler,1905,NaN,Grebler,1905,8.46793,Warren&Pearson,NaN,1905,8.46793
23,1906,103.525,1906,51.7691,85.45,3.43,Homer,1906,4.09698,Grebler,1906,NaN,Grebler,1906,8.46793,Warren&Pearson,NaN,1906,8.46793
24,1907,109.317,1907,49.5447,87.008,3.67,Homer,1907,4.52061,Grebler,1907,NaN,Grebler,1907,8.84851,Warren&Pearson,NaN,1907,8.84851
25,1908,100.819,1908,50.1257,88.71,3.87,Homer,1908,4.07957,Grebler,1908,NaN,Grebler,1908,8.65826,Warren&Pearson,NaN,1908,8.65826
26,1909,95.3804,1909,44.0717,90.49,3.76,Homer,1909,3.98673,Grebler,1909,NaN,Grebler,1909,8.94367,Warren&Pearson,NaN,1909,8.94367
27,1910,93.1106,1910,37.9818,92.407,3.91,Homer,1910,4.3059,Grebler,1910,NaN,Grebler,1910,9.89517,Warren&Pearson,NaN,1910,9.89517
28,1911,97.5433,1911,42.2976,93.863,3.98,Homer,1911,4.20724,Grebler,1911,NaN,Grebler,1911,9.22909,Warren&Pearson,NaN,1911,9.22909
29,1912,102.365,1912,42.2541,95.335,4.01,Homer,1912,4.36973,Grebler,1912,NaN,Grebler,1912,9.134,Warren&Pearson,NaN,1912,9.134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,2016.71,163.128,NaN,NaN,NaN,NaN,NaN,2016.71,184.059,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.71,241.428,BLS,NaN,NaN,NaN
835,2016.79,162.997,NaN,NaN,NaN,NaN,NaN,2016.79,184.141,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.79,241.729,BLS,NaN,NaN,NaN
836,2016.87,163.448,NaN,NaN,NaN,NaN,NaN,2016.87,184.363,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.87,241.353,BLS,NaN,NaN,NaN
837,2016.96,163.552,NaN,NaN,NaN,NaN,NaN,2016.96,184.541,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2016.96,241.432,BLS,NaN,NaN,NaN
838,2017.04,162.829,NaN,NaN,NaN,NaN,NaN,2017.04,184.795,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.04,242.839,BLS,NaN,NaN,NaN
839,2017.12,162.649,NaN,NaN,NaN,NaN,NaN,2017.12,185.172,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.12,243.603,BLS,NaN,NaN,NaN
840,2017.21,163.837,NaN,NaN,NaN,NaN,NaN,2017.21,186.676,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.21,243.801,BLS,NaN,NaN,NaN
841,2017.29,165.109,NaN,NaN,NaN,NaN,NaN,2017.29,188.683,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.29,244.524,BLS,NaN,NaN,NaN
842,2017.37,166.718,NaN,NaN,NaN,NaN,NaN,2017.37,190.685,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.37,244.733,BLS,NaN,NaN,NaN
843,2017.46,168.09,NaN,NaN,NaN,NaN,NaN,2017.46,192.428,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.46,244.955,BLS,NaN,NaN,NaN
844,2017.54,169.309,NaN,NaN,NaN,NaN,NaN,2017.54,193.69,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.54,244.786,BLS,NaN,NaN,NaN
845,2017.62,169.542,NaN,NaN,NaN,NaN,NaN,2017.62,194.538,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.62,245.519,BLS,NaN,NaN,NaN
846,2017.71,169.063,NaN,NaN,NaN,NaN,NaN,2017.71,195.015,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.71,246.819,BLS,NaN,NaN,NaN
847,2017.79,169.401,NaN,NaN,NaN,NaN,NaN,2017.79,195.282,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.79,246.663,BLS,NaN,NaN,NaN
848,2017.87,169.714,NaN,NaN,NaN,NaN,NaN,2017.87,195.647,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.87,246.669,BLS,NaN,NaN,NaN
849,2017.96,170.17,NaN,NaN,NaN,NaN,NaN,2017.96,196.058,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.96,246.524,BLS,NaN,NaN,NaN
850,2018.04,169.496,NaN,NaN,NaN,NaN,NaN,2018.04,196.345,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.04,247.867,BLS,NaN,NaN,NaN
851,2018.12,169.425,NaN,NaN,NaN,NaN,NaN,2018.12,197.152,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.12,248.991,BLS,NaN,NaN,NaN
852,2018.21,170.486,NaN,NaN,NaN,NaN,NaN,2018.21,198.836,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.21,249.554,BLS,NaN,NaN,NaN
853,2018.29,171.564,NaN,NaN,NaN,NaN,NaN,2018.29,200.888,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.29,250.546,BLS,NaN,NaN,NaN
854,2018.37,172.432,NaN,NaN,NaN,NaN,NaN,2018.37,202.745,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.37,251.588,BLS,NaN,NaN,NaN
855,2018.46,173.518,NaN,NaN,NaN,NaN,NaN,2018.46,204.347,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.46,251.989,BLS,NaN,NaN,NaN
856,2018.54,174.292,NaN,NaN,NaN,NaN,NaN,2018.54,205.272,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.54,252.006,BLS,NaN,NaN,NaN
857,2018.62,174.514,NaN,NaN,NaN,NaN,NaN,2018.62,205.647,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.62,252.146,BLS,NaN,NaN,NaN
858,2018.71,174.362,NaN,NaN,NaN,NaN,NaN,2018.71,205.707,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.71,252.439,BLS,NaN,NaN,NaN
859,2018.79,174.056,NaN,NaN,NaN,NaN,NaN,2018.79,205.709,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.79,252.885,BLS,NaN,NaN,NaN
860,2018.87,174.439,NaN,NaN,NaN,NaN,NaN,2018.87,205.471,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.87,252.038,BLS,NaN,NaN,NaN
861,2018.96,174.659,NaN,NaN,NaN,NaN,NaN,2018.96,205.073,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.96,251.233,BLS,NaN,NaN,NaN
862,2019.04,174.016,NaN,NaN,NaN,NaN,NaN,2019.04,204.708,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2019.04,251.712,BLS,NaN,NaN,NaN
863,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.12,252.776,BLS,NaN,NaN,NaN

In [7]:
data = pd.read_excel('http://www.econ.yale.edu/~shiller/data/Fig3-1.xls', header=None)

In [8]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,"U.S. Home Price and Related data, for Figure 3...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,See the book for description of data.,NaN,NaN,NaN,"Update Nominal Home Price Index, Click Additio...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Monthly data from January 1953 for prices, all...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nominal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Real,NaN,Real,NaN,NaN,NaN,NaN,Home,NaN,NaN,Nominal,NaN,NaN,Consumer,NaN,NaN,NaN,NaN
4,NaN,Home,NaN,Building,U.S.,NaN,NaN,NaN,Price,HPI,NaN,Building,NaN,NaN,Price,CPI Annual&,NaN,NaN,NaN
5,NaN,Price,NaN,Cost,Population,NaN,Long Rate,NaN,Index,Source,NaN,Cost,Build Cost,NaN,Index,Quarterly,NaN,NaN,CPI
6,Date,Index,Date,Index,Millions,Long Rate,Source,Date,From fig2.1Revised2011.xls,NaN,Date,Index,Source,Date,NaN,NaN,NaN,Date,Annual
7,1890,100,1890,51.3623,63.056,3.42,Homer,1890,3.5573,Grebler,1890,NaN,Grebler,1890,7.61165,Warren&Pearson,NaN,1890,7.61165
8,1891,88.0118,1891,47.2662,64.361,3.62,Homer,1891,3.20911,Grebler,1891,NaN,Grebler,1891,7.80194,Warren&Pearson,NaN,1891,7.80194
9,1892,95.4217,1892,52.0482,65.666,3.6,Homer,1892,3.26714,Grebler,1892,NaN,Grebler,1892,7.32621,Warren&Pearson,NaN,1892,7.32621
10,1893,92.2974,1893,44.6733,66.97,3.75,Homer,1893,3.40642,Grebler,1893,NaN,Grebler,1893,7.89709,Warren&Pearson,NaN,1893,7.89709
11,1894,123.98,1894,57.2634,68.275,3.7,Homer,1894,3.96932,Grebler,1894,NaN,Grebler,1894,6.85048,Warren&Pearson,NaN,1894,6.85048
12,1895,117.455,1895,61.4703,69.58,3.46,Homer,1895,3.60372,Grebler,1895,NaN,Grebler,1895,6.56505,Warren&Pearson,NaN,1895,6.56505
13,1896,100.303,1896,60.0689,70.885,3.6,Homer,1896,3.12206,Grebler,1896,NaN,Grebler,1896,6.66019,Warren&Pearson,NaN,1896,6.66019
14,1897,106.516,1897,62.3849,72.189,3.4,Homer,1897,3.22072,Grebler,1897,NaN,Grebler,1897,6.4699,Warren&Pearson,NaN,1897,6.4699
15,1898,110.184,1898,61.438,73.494,3.35,Homer,1898,3.42963,Grebler,1898,NaN,Grebler,1898,6.66019,Warren&Pearson,NaN,1898,6.66019
16,1899,103.853,1899,64.0446,74.799,3.1,Homer,1899,3.27875,Grebler,1899,NaN,Grebler,1899,6.75534,Warren&Pearson,NaN,1899,6.75534
17,1900,101.574,1900,49.4206,76.094,3.15,Homer,1900,3.7488,Grebler,1900,NaN,Grebler,1900,7.89709,Warren&Pearson,NaN,1900,7.89709
18,1901,87.3261,1901,51.2523,77.584,3.1,Homer,1901,3.14528,Grebler,1901,NaN,Grebler,1901,7.70679,Warren&Pearson,NaN,1901,7.70679
19,1902,100.474,1902,50.5162,79.163,3.18,Homer,1902,3.70818,Grebler,1902,NaN,Grebler,1902,7.89709,Warren&Pearson,NaN,1902,7.89709
20,1903,93.0749,1903,43.5435,80.632,3.3,Homer,1903,3.76621,Grebler,1903,NaN,Grebler,1903,8.65826,Warren&Pearson,NaN,1903,8.65826
21,1904,101.854,1904,47.0856,82.166,3.4,Homer,1904,3.9403,Grebler,1904,NaN,Grebler,1904,8.27768,Warren&Pearson,NaN,1904,8.27768
22,1905,87.2485,1905,47.111,83.822,3.48,Homer,1905,3.45284,Grebler,1905,NaN,Grebler,1905,8.46793,Warren&Pearson,NaN,1905,8.46793
23,1906,103.525,1906,51.7691,85.45,3.43,Homer,1906,4.09698,Grebler,1906,NaN,Grebler,1906,8.46793,Warren&Pearson,NaN,1906,8.46793
24,1907,109.317,1907,49.5447,87.008,3.67,Homer,1907,4.52061,Grebler,1907,NaN,Grebler,1907,8.84851,Warren&Pearson,NaN,1907,8.84851
25,1908,100.819,1908,50.1257,88.71,3.87,Homer,1908,4.07957,Grebler,1908,NaN,Grebler,1908,8.65826,Warren&Pearson,NaN,1908,8.65826
26,1909,95.3804,1909,44.0717,90.49,3.76,Homer,1909,3.98673,Grebler,1909,NaN,Grebler,1909,8.94367,Warren&Pearson,NaN,1909,8.94367
27,1910,93.1106,1910,37.9818,92.407,3.91,Homer,1910,4.3059,Grebler,1910,NaN,Grebler,1910,9.89517,Warren&Pearson,NaN,1910,9.89517
28,1911,97.5433,1911,42.2976,93.863,3.98,Homer,1911,4.20724,Grebler,1911,NaN,Grebler,1911,9.22909,Warren&Pearson,NaN,1911,9.22909
29,1912,102.365,1912,42.2541,95.335,4.01,Homer,1912,4.36973,Grebler,1912,NaN,Grebler,1912,9.134,Warren&Pearson,NaN,1912,9.134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
841,2017.29,165.079,NaN,NaN,NaN,NaN,NaN,2017.29,188.649,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.29,244.524,BLS,NaN,NaN,NaN
842,2017.37,166.689,NaN,NaN,NaN,NaN,NaN,2017.37,190.652,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.37,244.733,BLS,NaN,NaN,NaN
843,2017.46,168.062,NaN,NaN,NaN,NaN,NaN,2017.46,192.396,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.46,244.955,BLS,NaN,NaN,NaN
844,2017.54,169.278,NaN,NaN,NaN,NaN,NaN,2017.54,193.655,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.54,244.786,BLS,NaN,NaN,NaN
845,2017.62,169.507,NaN,NaN,NaN,NaN,NaN,2017.62,194.498,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.62,245.519,BLS,NaN,NaN,NaN
846,2017.71,169.026,NaN,NaN,NaN,NaN,NaN,2017.71,194.972,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.71,246.819,BLS,NaN,NaN,NaN
847,2017.79,169.364,NaN,NaN,NaN,NaN,NaN,2017.79,195.239,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.79,246.663,BLS,NaN,NaN,NaN
848,2017.87,169.679,NaN,NaN,NaN,NaN,NaN,2017.87,195.607,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.87,246.669,BLS,NaN,NaN,NaN
849,2017.96,170.131,NaN,NaN,NaN,NaN,NaN,2017.96,196.013,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2017.96,246.524,BLS,NaN,NaN,NaN
850,2018.04,169.447,NaN,NaN,NaN,NaN,NaN,2018.04,196.288,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.04,247.867,BLS,NaN,NaN,NaN
851,2018.12,169.364,NaN,NaN,NaN,NaN,NaN,2018.12,197.081,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.12,248.991,BLS,NaN,NaN,NaN
852,2018.21,170.415,NaN,NaN,NaN,NaN,NaN,2018.21,198.753,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.21,249.554,BLS,NaN,NaN,NaN
853,2018.29,171.487,NaN,NaN,NaN,NaN,NaN,2018.29,200.798,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.29,250.546,BLS,NaN,NaN,NaN
854,2018.37,172.359,NaN,NaN,NaN,NaN,NaN,2018.37,202.659,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.37,251.588,BLS,NaN,NaN,NaN
855,2018.46,173.445,NaN,NaN,NaN,NaN,NaN,2018.46,204.261,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.46,251.989,BLS,NaN,NaN,NaN
856,2018.54,174.213,NaN,NaN,NaN,NaN,NaN,2018.54,205.179,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.54,252.006,BLS,NaN,NaN,NaN
857,2018.62,174.43,NaN,NaN,NaN,NaN,NaN,2018.62,205.548,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.62,252.146,BLS,NaN,NaN,NaN
858,2018.71,174.265,NaN,NaN,NaN,NaN,NaN,2018.71,205.593,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.71,252.439,BLS,NaN,NaN,NaN
859,2018.79,173.951,NaN,NaN,NaN,NaN,NaN,2018.79,205.585,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.79,252.885,BLS,NaN,NaN,NaN
860,2018.87,174.32,NaN,NaN,NaN,NaN,NaN,2018.87,205.331,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.87,252.038,BLS,NaN,NaN,NaN
861,2018.96,174.532,NaN,NaN,NaN,NaN,NaN,2018.96,204.924,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2018.96,251.233,BLS,NaN,NaN,NaN
862,2019.04,173.793,NaN,NaN,NaN,NaN,NaN,2019.04,204.445,S&P/CoreLogic/Case-Shiller,NaN,NaN,NaN,2019.04,251.712,BLS,NaN,NaN,NaN
863,2019.12,173.271,NaN,NaN,NaN,NaN,NaN,2019.12,204.693,NaN,NaN,NaN,NaN,2019.12,252.776,BLS,NaN,NaN,NaN
864,2019.21,173.43,NaN,NaN,NaN,NaN,NaN,2019.21,206.036,NaN,NaN,NaN,NaN,2019.21,254.202,BLS,NaN,NaN,NaN
865,2019.29,174.113,NaN,NaN,NaN,NaN,NaN,2019.29,207.943,NaN,NaN,NaN,NaN,2019.29,255.548,BLS,NaN,NaN,NaN
866,2019.37,175.147,NaN,NaN,NaN,NaN,NaN,2019.37,209.624,NaN,NaN,NaN,NaN,2019.37,256.092,BLS,NaN,NaN,NaN
867,2019.46,176.131,NaN,NaN,NaN,NaN,NaN,2019.46,210.843,NaN,NaN,NaN,NaN,2019.46,256.143,BLS,NaN,NaN,NaN
868,2019.54,176.456,NaN,NaN,NaN,NaN,NaN,2019.54,211.585,NaN,NaN,NaN,NaN,2019.54,256.571,BLS,NaN,NaN,NaN
869,2019.62,176.767,NaN,NaN,NaN,NaN,NaN,2019.62,211.947,NaN,NaN,NaN,NaN,2019.62,256.558,BLS,NaN,NaN,NaN
870,2019.71,176.842,NaN,NaN,NaN,NaN,NaN,2019.71,212.203,NaN,NaN,NaN,NaN,2019.71,256.759,BLS,NaN,NaN,NaN

In [10]:
data = pd.read_excel("nakladnaya.xls", header=None, skiprows=2)#
data

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,NaN,NaN,НАКЛАДНАЯ,"№ 5764809 от ""08"" апреля 2018 г.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Грузоотправитель:,NaN,"ООО ""Первый строитель""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Грузополучатель:,NaN,"ООО ""Стройка века""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Основание для отпуска: Договор №,NaN,NaN,86,"от ""02""апреля 2018 г.",NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,№,Наименование товарно-материальных ценностей,NaN,NaN,NaN,Ед. изм.,NaN,NaN,Количество,NaN,"Цена,","Сумма,"
10,NaN,п/п,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,руб. коп.,руб. коп.
11,NaN,1,"Велосипед ""Спринтер""",NaN,NaN,NaN,шт,NaN,NaN,5,NaN,9000,45000
12,NaN,2,"Велосипед ""Малютка""",NaN,NaN,NaN,шт,NaN,NaN,10,NaN,3500,35000
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,Всего отпущено,2 (два) наименования,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,На сумму,80 000 (восемьдесят тысяч) рублей,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,Отпуск разрешил,Зам. Директора,NaN,NaN,NaN,NaN,Куликов,NaN,NaN,Куликов П.Д.,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,М.П.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,Отпустил,Кладовщик,NaN,NaN,NaN,NaN,Мазов,NaN,NaN,Мазов Р.К.,NaN
23,NaN,NaN,Получил,Водитель,NaN,NaN,NaN,NaN,Дроценко,NaN,NaN,Дроценко А.С.,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,М.П.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
data = pd.read_excel("nakladnaya.xls", header=None)
data=data.dropna(how = 'all')
data

,0,1,2,3,4,5,6,7,8,9,10,11,12
2,NaN,NaN,NaN,НАКЛАДНАЯ,"№ 5764809 от ""08"" апреля 2018 г.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Грузоотправитель:,NaN,"ООО ""Первый строитель""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Грузополучатель:,NaN,"ООО ""Стройка века""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Основание для отпуска: Договор №,NaN,NaN,86,"от ""02""апреля 2018 г.",NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,№,Наименование товарно-материальных ценностей,NaN,NaN,NaN,Ед. изм.,NaN,NaN,Количество,NaN,"Цена,","Сумма,"
12,NaN,п/п,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,руб. коп.,руб. коп.
13,NaN,1,"Велосипед ""Спринтер""",NaN,NaN,NaN,шт,NaN,NaN,5,NaN,9000,45000
14,NaN,2,"Велосипед ""Малютка""",NaN,NaN,NaN,шт,NaN,NaN,10,NaN,3500,35000
16,NaN,NaN,Всего отпущено,2 (два) наименования,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,На сумму,80 000 (восемьдесят тысяч) рублей,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,Отпуск разрешил,Зам. Директора,NaN,NaN,NaN,NaN,Куликов,NaN,NaN,Куликов П.Д.,NaN
22,NaN,NaN,М.П.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,Отпустил,Кладовщик,NaN,NaN,NaN,NaN,Мазов,NaN,NaN,Мазов Р.К.,NaN
25,NaN,NaN,Получил,Водитель,NaN,NaN,NaN,NaN,Дроценко,NaN,NaN,Дроценко А.С.,NaN
27,NaN,NaN,М.П.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
data.iloc[0, 4][2:9]

'5764809'

In [16]:
data.iloc[0, 4].split('от')[0]

'№ 5764809  '

In [33]:
data = pd.read_excel("nakladnaya.xls", header=None)
data=data.dropna(how = 'all')
#data.iloc[6:8, [1, 2, 6, 9, 11, 12]]
#data.iloc[6:8, :].dropna(axis=1, how='all')
data.iloc[6:8, :].dropna(axis=1, how='any')

   1                      2   6   9     11     12
13  1  Велосипед "Спринтер"   шт   5  9000  45000
14  2    Велосипед "Малютка"  шт  10  3500  35000

In [50]:
table = data.iloc[6:8, :].dropna(axis=1, how='any')
table

   1                      2   6   9     11     12
13  1  Велосипед "Спринтер"   шт   5  9000  45000
14  2    Велосипед "Малютка"  шт  10  3500  35000

In [40]:
table.to_excel("table.xls")

In [51]:
writer = pd.ExcelWriter('test.xlsx')  
table.to_excel(writer, index=False, sheet_name='Таблица')

In [52]:
workbook = writer.book  
worksheet = writer.sheets['Таблица']

In [53]:
money_fmt = workbook.add_format({'bold': True})  
name_fmt = workbook.add_format({'color': 'red'})

In [54]:
worksheet.set_column('E:F', 20, money_fmt)  
worksheet.set_column(1, 1, 20, name_fmt)

0

In [55]:
writer.save()