In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data_sf.xls')

In [98]:
df.head(250)

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF,84,95,...,75,96,33,28,26,6,11,15,14,8
1,1,Cristiano Ronaldo,33,Portugal,Juventus,77000000,405000,ST,84,94,...,85,95,28,31,23,7,11,15,14,11
2,2,Neymar Jr,26,Brazil,Paris Saint-Germain,118500000,290000,LW,79,87,...,81,94,27,24,33,9,9,15,15,11
3,3,De Gea,27,Spain,Manchester United,72000000,260000,GK,17,13,...,40,68,15,21,13,90,85,87,88,94
4,4,K. De Bruyne,27,Belgium,Manchester City,102000000,355000,RCM,93,82,...,79,88,68,58,51,15,13,5,10,13
5,5,E. Hazard,27,Belgium,Chelsea,93000000,340000,LF,81,84,...,86,91,34,27,22,11,12,6,8,8
6,6,L. Modrić,32,Croatia,Real Madrid,67000000,420000,RCM,86,72,...,82,84,60,76,73,13,9,7,14,9
7,7,L. Suárez,31,Uruguay,FC Barcelona,80000000,455000,RS,77,93,...,85,85,62,45,38,27,25,31,33,37
8,8,Sergio Ramos,32,Spain,Real Madrid,51000000,380000,RCB,66,60,...,75,82,87,92,91,11,8,9,7,11
9,9,J. Oblak,25,Slovenia,Atlético Madrid,68000000,94000,GK,13,11,...,11,70,27,12,18,86,92,78,88,89
10,10,R. Lewandowski,29,Poland,FC Bayern München,77000000,205000,ST,62,91,...,88,86,34,42,19,15,6,12,8,10
11,11,T. Kroos,28,Germany,Real Madrid,76500000,355000,LCM,88,76,...,73,85,72,79,69,10,11,13,7,10
12,12,D. Godín,32,Uruguay,Atlético Madrid,44000000,125000,CB,55,42,...,50,82,90,89,89,6,8,15,5,15
13,13,David Silva,32,Spain,Manchester City,60000000,285000,LCM,84,76,...,75,93,59,53,29,6,15,7,6,12
14,14,N. Kanté,27,France,Chelsea,63000000,225000,LDM,68,65,...,54,85,90,91,85,15,12,10,7,10
15,15,P. Dybala,24,Argentina,Juventus,89000000,205000,LF,82,84,...,86,84,23,20,20,5,4,4,5,8
16,16,H. Kane,24,England,Tottenham Hotspur,83500000,205000,ST,75,94,...,90,89,56,36,38,8,10,11,14,11
17,17,A. Griezmann,27,France,Atlético Madrid,78000000,145000,CAM,82,90,...,79,87,59,47,48,14,8,14,13,14
18,18,M. ter Stegen,26,Germany,FC Barcelona,58000000,240000,GK,15,14,...,25,69,25,13,10,87,85,88,85,90
19,19,T. Courtois,26,Belgium,Real Madrid,53500000,240000,GK,14,14,...,27,66,20,18,16,85,91,72,86,88
20,20,Sergio Busquets,29,Spain,FC Barcelona,51500000,315000,CDM,62,67,...,60,90,90,86,80,5,8,13,9,13
21,21,E. Cavani,31,Uruguay,Paris Saint-Germain,60000000,200000,LS,70,89,...,85,82,52,45,39,12,5,13,13,10
22,22,M. Neuer,32,Germany,FC Bayern München,38000000,130000,GK,15,13,...,47,70,17,10,11,90,86,91,87,87
23,23,S. Agüero,30,Argentina,Manchester City,64500000,300000,ST,70,93,...,83,90,30,20,12,13,15,6,11,14
24,24,G. Chiellini,33,Italy,Juventus,27000000,215000,LCB,58,33,...,50,84,93,93,90,3,3,2,4,3
25,25,K. Mbappé,19,France,Paris Saint-Germain,81000000,100000,RM,77,88,...,70,86,34,34,32,13,5,7,11,6
26,26,M. Salah,26,Egypt,Liverpool,69500000,255000,RM,78,90,...,61,91,38,43,41,14,14,9,11,14
27,27,Casemiro,26,Brazil,Real Madrid,59500000,285000,CDM,52,59,...,66,84,88,90,87,13,14,16,12,12
28,28,J. Rodríguez,26,Colombia,FC Bayern München,69500000,315000,LAM,90,83,...,81,87,52,41,44,15,15,15,5,14
29,29,L. Insigne,27,Italy,Napoli,62000000,165000,LW,86,77,...,61,83,51,24,22,8,4,14,9,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,220,M. Parolo,33,Italy,Lazio,9000000,59000,RDM,70,70,...,45,78,78,80,82,13,9,6,7,9
221,221,L. Fejsa,29,Serbia,SL Benfica,17000000,18000,CDM,50,49,...,56,75,82,84,77,14,12,13,11,14
222,222,G. Wijnaldum,27,Netherlands,Liverpool,23000000,130000,CAM,67,70,...,74,82,74,75,65,16,6,14,12,6
223,223,F. Fazio,31,Argentina,Roma,15000000,73000,LCB,44,41,...,26,86,85,85,78,8,9,12,11,14
224,224,O. Giroud,31,France,Chelsea,20000000,140000,ST,64,83,...,83,78,37,37,20,12,15,11,6,5
225,225,Marcano,31,Spain,Roma,15000000,73000,CB,49,43,...,45,72,85,84,80,8,16,7,14,16
226,226,A. Guardado,31,Mexico,Real Betis,19000000,35000,CM,73,60,...,70,76,75,75,73,7,10,10,11,10
227,227,E. Garay,31,Argentina,Valencia CF,15000000,44000,RCB,62,58,...,69,78,82,83,81,14,6,13,13,14
228,228,David Villa,36,Spain,New York City FC,8000000,12000,ST,71,86,...,88,83,30,28,38,8,9,9,11,9
229,229,Aduriz,37,Spain,Athletic Club de Bilbao,8000000,29000,ST,54,83,...,82,87,58,44,49,14,10,9,15,9
230,230,P. Čech,36,Czech Republic,Arsenal,3000000,60000,GK,19,12,...,23,63,12,13,12,78,82,70,83,79
231,231,M. Rashford,20,England,Manchester United,27000000,110000,LW,75,78,...,74,73,32,40,33,11,6,15,7,14
232,232,Laure Santeiro,30,Brazil,Fluminense,17000000,40000,CAM,73,72,...,74,77,29,13,23,9,7,8,14,10
233,233,M. Akanji,22,Switzerland,Borussia Dortmund,21000000,49000,LCB,51,36,...,40,76,82,84,80,10,9,13,6,9
234,234,F. de Jong,21,Netherlands,Ajax,26000000,19000,LDM,75,52,...,45,86,69,73,70,7,13,10,10,9
235,235,Nélson Semedo,24,Portugal,FC Barcelona,20000000,125000,RB,74,50,...,38,75,75,78,79,16,12,10,14,12
236,236,Pablo Fornals,22,Spain,Villarreal CF,24000000,36000,CAM,74,77,...,46,71,72,74,73,9,11,12,7,15
237,237,Fabián,22,Spain,Napoli,26000000,64000,LM,72,79,...,67,77,70,78,75,16,11,7,13,13
238,238,E. Bailly,24,Ivory Coast,Manchester United,21000000,105000,CB,51,33,...,46,70,80,82,83,14,14,10,9,8
239,239,Dani Ceballos,21,Spain,Real Madrid,25000000,120000,LCM,74,68,...,55,80,62,75,74,12,15,16,7,13
240,240,H. Lozano,22,Mexico,PSV,24000000,22000,LS,75,77,...,64,77,45,35,29,11,10,14,14,10
241,241,Morales,30,Spain,Levante UD,17000000,33000,LS,79,80,...,76,83,63,54,45,14,13,13,16,8
242,242,T. Strakosha,23,Albania,Lazio,17000000,36000,GK,18,18,...,21,61,20,18,12,81,77,75,78,86
243,243,E. Hysaj,24,Albania,Napoli,20000000,58000,RB,78,47,...,40,76,80,81,80,12,6,14,9,11
244,244,Ricardo Pereira,24,Portugal,Leicester City,19000000,64000,RB,81,61,...,60,81,76,80,75,16,12,15,11,11
245,245,R. Guerreiro,24,Portugal,Borussia Dortmund,24000000,54000,LM,85,75,...,44,75,67,70,77,12,6,8,11,8
246,246,C. Bacca,31,Colombia,Villarreal CF,16000000,45000,LS,60,84,...,80,78,40,16,14,12,12,8,5,8
247,247,A. Plea,25,France,Borussia Mönchengladbach,22000000,40000,LW,78,82,...,65,76,29,40,30,11,15,16,12,15
248,248,B. Mendy,23,France,Manchester City,20000000,105000,LB,87,33,...,50,79,78,79,81,7,7,9,15,9
249,249,C. Kramer,27,Germany,Borussia Mönchengladbach,17000000,35000,CDM,61,45,...,47,78,80,80,76,8,13,9,6,8

In [3]:
small_df = df[df.columns[1:8]].head(25)
small_df

,Name,Age,Nationality,Club,Value,Wage,Position
0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF
1,Cristiano Ronaldo,33,Portugal,Juventus,77000000,405000,ST
2,Neymar Jr,26,Brazil,Paris Saint-Germain,118500000,290000,LW
3,De Gea,27,Spain,Manchester United,72000000,260000,GK
4,K. De Bruyne,27,Belgium,Manchester City,102000000,355000,RCM
5,E. Hazard,27,Belgium,Chelsea,93000000,340000,LF
6,L. Modrić,32,Croatia,Real Madrid,67000000,420000,RCM
7,L. Suárez,31,Uruguay,FC Barcelona,80000000,455000,RS
8,Sergio Ramos,32,Spain,Real Madrid,51000000,380000,RCB
9,J. Oblak,25,Slovenia,Atlético Madrid,68000000,94000,GK
10,R. Lewandowski,29,Poland,FC Bayern München,77000000,205000,ST
11,T. Kroos,28,Germany,Real Madrid,76500000,355000,LCM
12,D. Godín,32,Uruguay,Atlético Madrid,44000000,125000,CB
13,David Silva,32,Spain,Manchester City,60000000,285000,LCM
14,N. Kanté,27,France,Chelsea,63000000,225000,LDM
15,P. Dybala,24,Argentina,Juventus,89000000,205000,LF
16,H. Kane,24,England,Tottenham Hotspur,83500000,205000,ST
17,A. Griezmann,27,France,Atlético Madrid,78000000,145000,CAM
18,M. ter Stegen,26,Germany,FC Barcelona,58000000,240000,GK
19,T. Courtois,26,Belgium,Real Madrid,53500000,240000,GK
20,Sergio Busquets,29,Spain,FC Barcelona,51500000,315000,CDM
21,E. Cavani,31,Uruguay,Paris Saint-Germain,60000000,200000,LS
22,M. Neuer,32,Germany,FC Bayern München,38000000,130000,GK
23,S. Agüero,30,Argentina,Manchester City,64500000,300000,ST
24,G. Chiellini,33,Italy,Juventus,27000000,215000,LCB

In [6]:
s = small_df['Nationality'].value_counts()
display(s)

Spain        4
Uruguay      3
Germany      3
Argentina    3
Belgium      3
France       2
Portugal     1
Italy        1
Poland       1
England      1
Croatia      1
Brazil       1
Slovenia     1
Name: Nationality, dtype: int64

In [7]:
s = small_df.Nationality.value_counts()
display(s)

Spain        4
Belgium      3
Argentina    3
Germany      3
Uruguay      3
France       2
Slovenia     1
Croatia      1
England      1
Italy        1
Poland       1
Portugal     1
Brazil       1
Name: Nationality, dtype: int64

In [8]:
s.index

Index(['Spain', 'Belgium', 'Argentina', 'Germany', 'Uruguay', 'France',
       'Slovenia', 'Croatia', 'England', 'Italy', 'Poland', 'Portugal',
       'Brazil'],
      dtype='object')

In [9]:
s.index[0]

'Spain'

In [10]:
len(s.index)

13

In [11]:
len(s)

13

In [12]:
s['Germany']

3

In [13]:
s.Germany

3

In [14]:
s.loc[s > 1]

Spain        4
Belgium      3
Argentina    3
Germany      3
Uruguay      3
France       2
Name: Nationality, dtype: int64

In [15]:
s[s > 1]

Spain        4
Belgium      3
Argentina    3
Germany      3
Uruguay      3
France       2
Name: Nationality, dtype: int64

In [16]:
s = small_df['Club'].value_counts()
display(s)

Real Madrid            4
FC Barcelona           4
Juventus               3
Manchester City        3
Atlético Madrid        3
Paris Saint-Germain    2
Chelsea                2
FC Bayern München      2
Manchester United      1
Tottenham Hotspur      1
Name: Club, dtype: int64

In [17]:
len(s)

10

In [18]:
s = df['Club'].value_counts()
display(s)

V-Varen Nagasaki             30
Shonan Bellmare              30
FC Emmen                     29
Vissel Kobe                  29
De Graafschap                29
Padova                       29
FC Energie Cottbus           28
Al Batin                     28
Livingston FC                28
Doncaster Rovers             28
Gillingham                   28
Sangju Sangmu FC             28
Bury                         28
Morecambe                    28
Coventry City                28
Accrington Stanley           28
San Martín de San Juan       28
Yeovil Town                  28
Mansfield Town               28
Júbilo Iwata                 28
Colchester United            28
Curicó Unido                 28
Blackpool                    28
Lincoln City                 28
Cambridge United             28
Cosenza                      28
Sagan Tosu                   28
Northampton Town             28
Crewe Alexandra              28
Southend United              28
                             ..
En Avant de Guingamp         10
Derby County                 10
Celtic                       10
AZ Alkmaar                   10
Fluminense                   10
Royal Antwerp FC             10
KRC Genk                     10
Fenerbahçe SK                10
Clube Sport Marítimo         10
Botafogo                     10
PAOK                         10
Fiorentina                   10
Shakhtar Donetsk             10
1. FC Köln                   10
Kasimpaşa SK                  9
Cagliari                      9
Udinese                       9
América FC (Minas Gerais)     9
KAA Gent                      9
Internacional                 9
Club Brugge KV                9
OGC Nice                      9
FC Metz                       8
Cruzeiro                      8
Dijon FCO                     8
Olympiacos CFP                8
Dinamo Zagreb                 7
GD Chaves                     7
Vitória Guimarães             7
Atlético Mineiro              6
Name: Club, Length: 650, dtype: int64

In [19]:
len(s)

650

In [20]:
s = small_df['Nationality'].value_counts(normalize=True)
display(s)

Spain        0.16
Belgium      0.12
Argentina    0.12
Germany      0.12
Uruguay      0.12
France       0.08
Slovenia     0.04
Croatia      0.04
England      0.04
Italy        0.04
Poland       0.04
Portugal     0.04
Brazil       0.04
Name: Nationality, dtype: float64

In [24]:
s = df['Position'].value_counts(normalize=True)
display(s)

GK     0.127239
ST     0.117237
CB     0.108785
CM     0.082732
LB     0.077692
RB     0.073505
RM     0.059394
LM     0.056447
CDM    0.053578
CAM    0.049081
RCB    0.032411
LCB    0.031713
LW     0.018764
RCM    0.018609
RW     0.018376
LCM    0.018066
LDM    0.011476
RDM    0.010700
LS     0.009382
RS     0.008839
RWB    0.005428
LWB    0.004652
CF     0.003954
LF     0.000620
RF     0.000465
LAM    0.000465
RAM    0.000388
Name: Position, dtype: float64

In [25]:
s = small_df['Age'].value_counts()
display(s)

27    5
32    5
31    3
26    3
29    2
24    2
33    2
30    1
28    1
25    1
Name: Age, dtype: int64

In [26]:
s = small_df['Wage'].value_counts()
display(s)

205000    3
355000    2
240000    2
300000    1
130000    1
225000    1
455000    1
340000    1
315000    1
565000    1
405000    1
215000    1
380000    1
285000    1
145000    1
290000    1
125000    1
200000    1
420000    1
94000     1
260000    1
Name: Wage, dtype: int64

In [29]:
s = small_df['Wage'].value_counts(bins=4)
display(s)

(211750.0, 329500.0]     9
(93528.999, 211750.0]    8
(329500.0, 447250.0]     6
(447250.0, 565000.0]     2
Name: Wage, dtype: int64

In [30]:
small_df.loc[(small_df['Wage'] > s.index[3].left) & (small_df['Wage'] <= s.index[3].right)]

        Name  Age Nationality          Club      Value    Wage Position
0   L. Messi   31   Argentina  FC Barcelona  110500000  565000       RF
7  L. Suárez   31     Uruguay  FC Barcelona   80000000  455000       RS

In [31]:
s.index

IntervalIndex([(211750.0, 329500.0], (93528.999, 211750.0], (329500.0, 447250.0], (447250.0, 565000.0]],
              closed='right',
              dtype='interval[float64]')

In [32]:
s.index[3]

Interval(447250.0, 565000.0, closed='right')

In [33]:
s.index[3].left

447250.0

In [34]:
s.index[3].right

565000.0

In [35]:
small_df['Wage'] > s.index[3].left

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
Name: Wage, dtype: bool

In [36]:
small_df[small_df['Wage'] > s.index[3].left]

        Name  Age Nationality          Club      Value    Wage Position
0   L. Messi   31   Argentina  FC Barcelona  110500000  565000       RF
7  L. Suárez   31     Uruguay  FC Barcelona   80000000  455000       RS

In [38]:
s = df['FKAccuracy'].value_counts(bins=5)
display(s)

(21.2, 39.4]     4859
(39.4, 57.6]     3957
(57.6, 75.8]     2108
(2.908, 21.2]    1760
(75.8, 94.0]      213
Name: FKAccuracy, dtype: int64

In [39]:
s = small_df['Nationality'].value_counts()
print(s.index)
print(len(s.index))

Index(['Spain', 'Belgium', 'Argentina', 'Germany', 'Uruguay', 'France',
       'Slovenia', 'Croatia', 'England', 'Italy', 'Poland', 'Portugal',
       'Brazil'],
      dtype='object')
13

In [40]:
small_df['Nationality'].unique()

array(['Argentina', 'Portugal', 'Brazil', 'Spain', 'Belgium', 'Croatia',
       'Uruguay', 'Slovenia', 'Poland', 'Germany', 'France', 'England',
       'Italy'], dtype=object)

In [41]:
len(small_df['Nationality'].unique())

13

In [42]:
small_df['Nationality'].nunique()

13

In [52]:
result = len(df['Position'].value_counts())
result

27

In [55]:
s = small_df['Nationality'].value_counts()
s_df = s.reset_index()
display(s_df)

        index  Nationality
0       Spain            4
1     Belgium            3
2   Argentina            3
3     Germany            3
4     Uruguay            3
5      France            2
6    Slovenia            1
7     Croatia            1
8     England            1
9       Italy            1
10     Poland            1
11   Portugal            1
12     Brazil            1

In [56]:
s_df.columns = ['Nationality','Players Count']
display(s_df)

   Nationality  Players Count
0        Spain              4
1      Belgium              3
2    Argentina              3
3      Germany              3
4      Uruguay              3
5       France              2
6     Slovenia              1
7      Croatia              1
8      England              1
9        Italy              1
10      Poland              1
11    Portugal              1
12      Brazil              1

In [ ]:
small_df[small_df['Wage'] > s.index[3].left]

In [61]:
df[df['Nationality'] == 'Spain']['Wage'].value_counts(bins=4, normalize=True)

(620.999, 95750.0]      0.970194
(95750.0, 190500.0]     0.016393
(190500.0, 285250.0]    0.008942
(285250.0, 380000.0]    0.004471
Name: Wage, dtype: float64

In [63]:
df[df['Club'] == 'Manchester United']['Nationality'].nunique()

13

In [70]:
df[(df['Nationality'] == 'Brazil') & (df['Club'] == 'Juventus')]

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
64,64,Alex Sandro,27,Brazil,Juventus,36500000,160000,LB,84,55,...,60,82,81,84,84,7,7,9,12,5
65,65,Douglas Costa,27,Brazil,Juventus,46500000,175000,LM,84,67,...,77,84,45,38,34,13,15,9,12,5

In [72]:
df[df['Age'] > 35]['Club'].value_counts()

Club Atlético Huracán            4
Hokkaido Consadole Sapporo       4
Estudiantes de La Plata          3
Hammarby IF                      3
San Martín de San Juan           3
Gimnasia y Esgrima La Plata      3
Nagoya Grampus                   3
Club Atlético Talleres           3
Club Atlético Colón              3
Club Atlético Tigre              3
Benevento                        3
Morecambe                        3
Rochdale                         2
Atlético Tucumán                 2
Once Caldas                      2
Al Hilal                         2
Livorno                          2
Lobos BUAP                       2
San Lorenzo de Almagro           2
Cork City                        2
Guizhou Hengfeng FC              2
Unión La Calera                  2
Kashima Antlers                  2
Empoli                           2
Elche CF                         2
Júbilo Iwata                     2
River Plate                      2
Atlético Bucaramanga             2
SV Zulte-Waregem                 2
Venezia FC                       2
                                ..
Mansfield Town                   1
Dundalk                          1
Piast Gliwice                    1
Palermo                          1
Coventry City                    1
Suwon Samsung Bluewings          1
Oldham Athletic                  1
AC Ajaccio                       1
IK Sirius                        1
Club Tijuana                     1
Akhisar Belediyespor             1
CD Universidad de Concepción     1
Al Taawoun                       1
Paris Saint-Germain              1
Pescara                          1
Melbourne City FC                1
Standard de Liège                1
Fortuna Düsseldorf               1
La Berrichonne de Châteauroux    1
Accrington Stanley               1
Girona FC                        1
Cracovia                         1
Independiente Santa Fe           1
Tromsø IL                        1
CD Tondela                       1
Athletic Club de Bilbao          1
Newell's Old Boys                1
New York City FC                 1
Birmingham City                  1
Swindon Town                     1
Name: Club, Length: 212, dtype: int64

In [78]:
df[df['Nationality'] == 'Argentina']['Age'].value_counts(bins = 4)

(22.25, 28.5]      200
(15.974, 22.25]    197
(28.5, 34.75]      128
(34.75, 41.0]       49
Name: Age, dtype: int64

In [80]:
df[df['Nationality'] == 'Spain']['Age'].value_counts(normalize=True)

21    0.117735
22    0.095380
20    0.077496
23    0.071535
25    0.064083
27    0.062593
24    0.059613
28    0.053651
26    0.053651
29    0.047690
19    0.047690
18    0.038748
30    0.038748
31    0.032787
32    0.032787
33    0.031297
34    0.022355
17    0.013413
35    0.011923
36    0.010432
37    0.008942
39    0.002981
16    0.002981
38    0.001490
Name: Age, dtype: float64

In [7]:
df.groupby(['Club'])

In [8]:
df.groupby(['Club']).groups

{' SSV Jahn Regensburg': Int64Index([ 1642,  2284,  2374,  2401,  2575,  2583,  2850,  2868,  3418,
              3908,  3989,  4154,  5151,  5177,  5525,  5885,  6070,  6679,
              7173,  7477,  8905,  9061, 10825, 12482],
            dtype='int64'),
 '1. FC Heidenheim 1846': Int64Index([ 1060,  1805,  1978,  2050,  2066,  2926,  3584,  3605,  4312,
              4457,  4783,  6818,  7160,  7166,  7460,  9475, 10052, 10565,
             11217, 12236],
            dtype='int64'),
 '1. FC Kaiserslautern': Int64Index([ 2931,  3590,  4270,  4413,  4475,  4483,  4709,  4779,  5079,
              5325,  5403,  5855,  5917,  7295,  8784,  9496,  9964, 10019,
             10122, 10671, 11500, 11970, 12222],
            dtype='int64'),
 '1. FC Köln': Int64Index([166, 379, 899, 1399, 3415, 6904, 7052, 8892, 12171, 12376], dtype='int64'),
 '1. FC Magdeburg': Int64Index([ 1967,  2069,  2152,  2569,  2886,  3030,  3300,  3332,  4436,
              4913,  5002,  5033,  5493,  5768,  6329,  7046,  7595,  8387,
              9626, 11125, 11400],
            dtype='int64'),
 '1. FC Nürnberg': Int64Index([724, 1208, 1254, 1920, 4775, 5265, 5556, 5985, 8590, 8632, 9217,
             9858, 10480],
            dtype='int64'),
 '1. FC Union Berlin': Int64Index([1422, 1493, 2530, 2876, 3635, 3844, 4683, 4826, 11038, 11296,
             12340],
            dtype='int64'),
 '1. FSV Mainz 05': Int64Index([545, 670, 765, 1201, 1342, 6218, 6868, 8792, 10293, 10561, 10566], dtype='int64'),
 'AC Ajaccio': Int64Index([ 1507,  1672,  2118,  2180,  2798,  3046,  3742,  3879,  4522,
              4697,  5698,  6607,  7484,  8519,  9449, 11043, 11789, 12221,
             12244],
            dtype='int64'),
 'AC Horsens': Int64Index([ 2491,  2924,  3640,  3881,  5419,  5471,  5929,  6518,  6669,
              6736,  7115,  8049,  8203,  8237,  9281,  9804, 10251, 10454,
             11241, 11513, 11763, 12011, 12598, 12692, 12743],
            dtype='int64'),
 'AD Alcorcón': Int64Index([1407, 1607, 1651, 2117, 2216, 2619, 3011, 3177, 3278, 3601, 3801,
             4808, 6385, 6805, 7120, 7141, 7397, 8901, 9526],
            dtype='int64'),
 'ADO Den Haag': Int64Index([ 1377,  1825,  2976,  3037,  3611,  3783,  3825,  4555,  4969,
              5599,  6344,  6787,  6816,  8296,  8391,  9055,  9157, 10330,
             10506],
            dtype='int64'),
 'AEK Athens': Int64Index([700, 751, 754, 1180, 1309, 1356, 3314, 5304, 5975, 10026, 12119], dtype='int64'),
 'AFC Wimbledon': Int64Index([ 3464,  3868,  4990,  5292,  5566,  6228,  6526,  6566,  7070,
              7181,  7241,  7256,  7698,  7978,  8213,  8356,  9521, 10693,
             11132, 11318, 12078, 12139, 12142, 12239, 12266, 12679],
            dtype='int64'),
 'AIK': Int64Index([ 1451,  1961,  3323,  3466,  3651,  4274,  4615,  5201,  6418,
              7655,  8072,  8611,  9363, 11325, 11341, 11399, 11633, 11729,
             12386],
            dtype='int64'),
 'AJ Auxerre': Int64Index([ 1606,  2028,  2132,  2962,  3597,  4731,  4980,  5006,  5396,
              5542,  5626,  8419,  9728, 10420, 10471, 10849, 11520],
            dtype='int64'),
 'AS Béziers': Int64Index([ 1557,  4215,  4796,  5134,  5604,  5809,  5965,  6427,  6435,
              6558,  6867,  7590,  7730,  7870,  8428,  8540,  8587,  9981,
             10106, 10771, 10907, 10987, 11444, 11689, 11942],
            dtype='int64'),
 'AS Monaco': Int64Index([ 137,  172,  173,  298,  365,  400,  428,  475,  477,  918,  991,
             4009, 4487, 6278, 6431, 7588, 8046, 8314],
            dtype='int64'),
 'AS Nancy Lorraine': Int64Index([ 1995,  2169,  2428,  2432,  2943,  3209,  3237,  3289,  3457,
              3579,  3920,  4465,  5026,  5666,  5972,  6374,  6963,  7856,
              8468,  9543, 10306, 10854, 11260, 11746, 11906],
            dtype='int64'),
 'AS Saint-Étienne': Int64Index([  136,   725,   822,   897,  1314,  1394,  1913,  2643,  2702,
              6892,  8321,  9822, 10234, 10718, 11503],
            dtype='int64'),
 'AZ Alkmaar': Int64Index([849, 1158, 1246, 1768, 3458, 3891, 4207, 4842, 6039, 7059], dtype='int64'),
 'Aalborg BK': Int64Index([ 1458,  2509,  2646,  3862,  3922,  5707,  6119,  6555,  6715,
              7094,  7961,  9259,  9334, 10694, 11262, 11816, 12342, 12440,
             12510, 12520, 12652, 12758],
            dtype='int64'),
 'Aarhus GF': Int64Index([ 2318,  2610,  2936,  3490,  4530,  4546,  4855,  4886,  4920,
              4941,  5161,  6213,  6575,  7096,  7768,  8082,  9731, 11769,
             12301, 12570, 12574, 12580, 12634, 12663, 12700],
            dtype='int64'),
 'Aberdeen': Int64Index([ 2444,  2978,  3317,  3574,  4026,  4144,  4280,  4824,  4949,
              5524,  7444,  9203,  9943, 11232, 12248, 12425, 12675, 12765],
            dtype='int64'),
 'Accrington Stanley': Int64Index([ 2227,  2600,  3827,  4031,  4295,  5336,  5675,  6433,  6493,
              6554,  7891,  8074,  8508,  8518,  8928,  9515,  9782,  9940,
             10059, 10141, 10349, 10424, 10474, 10928, 11020, 12346, 12422,
             12456],
            dtype='int64'),
 'Adelaide United': Int64Index([ 1533,  2387,  2460,  3354,  3942,  4130,  4451,  4668,  6908,
              7090,  7252,  7706,  8316,  9212,  9623,  9980, 10220, 10458,
             12055, 12409, 12485, 12613, 12628, 12703],
            dtype='int64'),
 'Ajax': Int64Index([152, 188, 234, 300, 319, 352, 737, 1335, 3111, 3769, 4847, 4897,
             5010],
            dtype='int64'),
 'Akhisar Belediyespor': Int64Index([ 722,  796, 1781, 2049, 2096, 2594, 2617, 2699, 4929, 5376, 5589,
             6870, 7081, 8801],
            dtype='int64'),
 'Al Ahli': Int64Index([  419,   524,  1617,  1815,  2256,  2519,  2521,  3614,  4048,
              6163,  6794,  9114,  9636,  9922, 11292, 11330, 11380, 11724,
             11728, 11730, 11839, 12230],
            dtype='int64'),
 'Al Batin': Int64Index([ 1540,  1959,  2525,  3812,  4591,  4771,  7178,  7220,  8091,
              8146,  8288,  9275,  9606, 10196, 10688, 11035, 11042, 11170,
             11659, 12106, 12135, 12198, 12324, 12392, 12427, 12749, 12787,
             12788],
            dtype='int64'),
 'Al Faisaly': Int64Index([ 2021,  2514,  2522,  2644,  2693,  3217,  4859,  4867,  5059,
              5715,  6144,  6347,  7322,  7855,  8061,  9207,  9329, 10389,
             10880, 10944, 11011, 11012, 11172, 11403, 11554, 11696, 11739],
            dtype='int64'),
 'Al Fateh': Int64Index([ 1374,  2376,  3437,  4198,  4877,  5186,  6452,  6534,  6665,
              6907,  7471,  7840,  8279,  8652,  8874,  9086,  9819,  9960,
             10312, 11252, 11519, 12064, 12066, 12366, 12371, 12568, 12676],
            dtype='int64'),
 'Al Fayha': Int64Index([ 1252,  1760,  1822,  1850,  3191,  4563,  4919,  5253,  6574,
              6775,  6953,  7091,  7196,  7568,  7642,  7798,  8129,  8771,
             10323, 10887, 11245, 11312, 11446, 11693, 11933],
            dtype='int64'),
 'Al Hazem': Int64Index([ 2396,  3045,  3627,  4174,  6016,  6931,  7118,  7615,  8711,
              8846,  8864,  8869,  8959,  9105,  9262,  9437,  9448,  9793,
             10079, 10580, 10927, 11019, 11321, 11597, 11632, 11745, 12058],
            dtype='int64'),
 'Al Hilal': Int64Index([  281,   505,   653,  1061,  1269,  1316,  1479,  1778,  1915,
              2758,  3234,  4180,  4489,  4658,  5409,  7735,  9081,  9436,
              9451, 10328, 11340, 11475],
            dtype='int64'),
 'Al Ittihad': Int64Index([  682,  2358,  2369,  2445,  2707,  2782,  2884,  3831,  4338,
              5219,  6299,  6379,  6620,  7436,  7783,  7877,  9517, 10412,
             10469, 10486, 10885, 11919],
            dtype='int64'),
 'Al Nassr': Int64Index([  177,   469,   948,  1067,  1800,  1818,  2334,  2981,  3839,
              3850,  4047,  6387,  6998,  7276,  7511,  9979, 10414, 10423,
             11299, 11761, 12180, 12544, 12713],
            dtype='int64'),
 'Al Qadisiyah': Int64Index([ 2972,  3493,  3894,  4586,  5327,  5492,  5601,  5817,  5829,
              5880,  6598,  7095,  7438,  7527,  7774,  8917, 10110, 11088,
             11207, 11324, 11331, 11334, 11416, 11741, 11762, 12004],
            dtype='int64'),
 'Al Raed': Int64Index([ 2157,  2224,  4152,  5195,  5511,  6685,  8040,  8174,  8224,
              8310,  8591,  8610,  8744,  9087,  9353,  9488,  9846, 10378,
             10593, 11191, 12025, 12159, 12418, 12420, 12807],
            dtype='int64'),
 'Al Shabab': Int64Index([ 1898,  2464,  3138,  4181,  4307,  6207,  6285,  6399,  6434,
              7751,  8292,  8443,  8900,  9511,  9575,  9985, 10475, 10600,
             10803, 11578, 11714, 11784, 11785, 12584],
            dtype='int64'),
 'Al Taawoun': Int64Index([  975,  3703,  3724,  5197,  5418,  5792,  6366,  6744,  6789,
              6888,  7992,  8140,  8877,  9268,  9430,  9643,  9894, 10018,
             10938, 11136, 12343, 12367, 12512, 12525, 12770],
            dtype='int64'),
 'Al Wehda': Int64Index([  857,  1115,  1211,  1402,  1931,  4235,  4935,  5359,  6103,
              7060,  7394,  7620,  8887,  9073,  9523,  9704, 10130, 10452,
             10654, 11242, 11253, 11545, 11758, 11894],
            dtype='int64'),
 'Alanyaspor': Int64Index([ 1196,  1794,  2019,  2119,  2366,  2418,  2765,  3185,  3388,
              4542,  5156,  9179, 10845, 11054, 11086, 11353, 11619],
            dtype='int64'),
 'Albacete BP': Int64Index([ 1852,  2133,  2968,  3455,  3566,  3755,  5076,  5830,  6972,
              7036,  7078,  7493,  7778,  9163,  9903, 11498, 11504],
            dtype='int64'),
 'Alianza Petrolera': Int64Index([ 2327,  2381,  2395,  2992,  3008,  3139,  3608,  4442,  4623,
              4703,  4827,  5163,  5275,  6547,  7162,  7300,  7799,  7965,
              8079,  9427,  9552, 10155, 10807, 11156, 11347, 12039],
            dtype='int64'),
 'Amiens SC': Int64Index([  709,   768,   923,   925,  1088,  1395,  1719,  2925,  2935,
              6470,  8244,  8306,  9655,  9664, 10317, 10585, 10735],
            dtype='int64'),
 'América FC (Minas Gerais)': Int64Index([908, 2592, 2688, 2739, 2949, 4458, 4891, 5993, 6841], dtype='int64'),
 'América de Cali': Int64Index([ 1848,  2651,  3758,  3794,  3871,  3882,  4086,  4706,  4940,
              6191,  6549,  6989, 10925, 10990, 11202, 11604, 11734, 11991,
             12748],
            dtype='int64'),
 'Angers SCO': Int64Index([1218, 1820, 1882, 2048, 2312, 3910, 6468, 7204, 7462, 8679, 9265,
             10946],
            dtype='int64'),
 'Antalyaspor': Int64Index([  782,   788,  1952,  2207,  2309,  2493,  3346,  3359,  3412,
              3941,  4204,  6582,  6608,  7434,  7535,  9493,  9888, 10931,
             11442],
            dtype='int64'),
 'Argentinos Juniors': Int64Index([ 1391,  1923,  2171,  2952,  3961,  4757,  6281,  7820,  8371,
              8722,  8837,  9023,  9321,  9339,  9634, 10192, 10227, 10427,
             10661, 12681],
            dtype='int64'),
 'Arka Gdynia': Int64Index([ 1629,  3067,  3318,  4187,  4208,  4373,  4519,  4792,  5298,
              6709,  6803,  6873,  7908,  8385,  8685,  8865,  8998,  9151,
              9974, 10633, 11181, 11773, 11954, 12052, 12228, 12426],
            dtype='int64'),
 'Arsenal': Int64Index([   33,    74,    87,   126,   135,   194,   215,   230,   257,
               331,   380,   483,   570,  1416,  1603,  1979,  5283,  6398,
              6583,  7307,  8747,  9892, 10934],
            dtype='int64'),
 'Ascoli': Int64Index([ 2518,  2573,  2692,  3102,  3324,  3364,  3671,  3930,  4088,
              4406,  4712,  4858,  5469,  5786,  6139,  6594,  7461,  7738,
              7788,  7829,  9442, 10647, 10818, 11335, 12750],
            dtype='int64'),
 'Aston Villa': Int64Index([ 1108,  1184,  1193,  1639,  1753,  1779,  2837,  5065,  5588,
              8838, 10265, 10495, 12006, 12373, 12404],
            dtype='int64'),
 'Atalanta': Int64Index([140, 254, 436, 479, 481, 525, 708, 732, 1019, 3004, 6914, 7363,
             9585],
            dtype='int64'),
 'Athletic Club de Bilbao': Int64Index([197, 229, 323, 337, 384, 569, 664, 973, 1012, 1056, 6872, 8092,
             10085],
            dtype='int64'),
 'Atiker Konyaspor': Int64Index([ 886, 1009, 1155, 1348, 1591, 1773, 1795, 1868, 1945, 2114, 2896,
             3347, 4184, 5180, 6308, 8663],
            dtype='int64'),
 'Atlanta United': Int64Index([ 1057,  1333,  1613,  1754,  2187,  3305,  3333,  4550,  4632,
              5451,  5946,  6732,  7208,  7284,  7874,  7989,  9238, 10784,
             11048, 11050, 11463, 12167],
            dtype='int64'),
 'Atlético Bucaramanga': Int64Index([ 1284,  1706,  2165,  2273,  3681,  3732,  3762,  4735,  5457,
              5609,  5844,  6384,  6540,  6976,  7217,  7522,  7950,  8616,
             10337, 11016, 11022, 11326, 11978, 12189],
            dtype='int64'),
 'Atlético Huila': Int64Index([ 1767,  2342,  4411,  4669,  5560,  5683,  6893,  7635,  7697,
              7817,  8117,  8178,  8245,  9729, 10381, 10610, 10700, 10912,
             11075, 11840, 12247, 12263, 12330, 12629, 12738],
            dtype='int64'),
 'Atlético Madrid': Int64Index([    9,    12,    17,    83,    86,   100,   106,   111,   146,
               161,   189,   256,   423,  6623,  6654,  6900,  7296,  7404,
              7587,  8013,  8985,  9080,  9953, 10371, 10510],
            dtype='int64'),
 'Atlético Mineiro': Int64Index([855, 1409, 1935, 2036, 2150, 3371], dtype='int64'),
 'Atlético Nacional': Int64Index([1535, 3062, 3348, 3787, 5847, 6271, 8708, 11972, 12019, 12718,
             12843, 12872],
            dtype='int64'),
 'Atlético Paranaense': Int64Index([1129, 1255, 1589, 1604, 2159, 2473, 2534, 3097, 3428, 3958, 5882,
             6265, 7035],
            dtype='int64'),
 'Atlético Tucumán': Int64Index([ 1455,  1542,  1646,  1917,  2829,  3174,  3802,  3997,  4677,
              5276,  6850,  8320,  9923, 10635, 10673, 10812],
            dtype='int64'),
 'Audax Italiano': Int64Index([ 1788,  2002,  2168,  2443,  3855,  3913,  4007,  4353,  4793,
              5168,  5205,  5243,  6100,  6333,  6463,  7205,  8357,  8817,
              8881,  9362,  9407,  9984, 10641, 12199, 12667],
            dtype='int64'),
 'BB Erzurumspor': Int64Index([ 1718,  2067,  2687,  4535,  5055,  5674,  6475,  7045,  8510,
              8742,  8773,  9671, 10466, 10479, 10751, 11523, 12740],
            dtype='int64'),
 'BK Häcken': Int64Index([ 1955,  2086,  2971,  3153,  3463,  4129,  4481,  4500,  4788,
              5573,  5852,  6483,  6937,  7203,  8745, 10049, 11192, 11304,
             12009, 12205, 12232, 12478, 12715, 12792],
            dtype='int64'),
 'BSC Young Boys': Int64Index([  649,   771,  1250,  2357,  2664,  5449,  5767,  6220,  7575,
              9221,  9417, 11404, 11876, 12108, 12181],
            dtype='int64'),
 'Bahia': Int64Index([1247, 1263, 1623, 2260, 2315, 2404, 2629, 2945, 3955, 4347, 5816,
             6322],
            dtype='int64'),
 'Barnsley': Int64Index([ 2897,  3094,  3408,  3518,  4358,  5056,  5062,  6325,  6920,
              7265,  7780, 10744, 11512, 11516, 11756, 12007, 12060, 12237,
             12388, 12599, 12821],
            dtype='int64'),
 'Bayer 04 Leverkusen': Int64Index([  128,   181,   251,   255,   258,   270,   285,   373,   674,
               683,  1049,  2108,  8768, 10316, 10325],
            dtype='int64'),
 'Beijing Renhe FC': Int64Index([  332,   543,  3232,  5081,  5176,  5474,  6214,  6763,  7055,
              7502,  7882,  8073,  8294,  9120,  9933,  9939, 10906, 11246,
             11890, 11944, 12192, 12202, 12255, 12391, 12682, 12684, 12876],
            dtype='int64'),
 'Beijing Sinobo Guoan FC': Int64Index([  205,   563,  2291,  2695,  3319,  3529,  4315,  5333,  5643,
              5942,  6226,  7101,  7228,  8000,  8525,  8578,  9555,  9757,
             10766, 11509, 11536, 11704, 12466, 12846],
            dtype='int64'),
 'Belgrano de Córdoba': Int64Index([ 2254,  2550,  2682,  4328,  4375,  4473,  4794,  5380,  5927,
              6405,  7379,  7716,  8642,  9352,  9657, 10834, 11701, 11882,
             12056],
            dtype='int64'),
 'Benevento': Int64Index([1020, 1406, 1441, 1538, 3151, 3166, 3644, 4028, 6560, 7583, 9869,
             11790],
            dtype='int64'),
 'Beşiktaş JK': Int64Index([  108,   260,   441,   516,   536,   537,   720,   740,   753,
               850,  5864,  6044,  7333,  7386,  9330,  9696, 10281, 12744],
            dtype='int64'),
 'Birmingham City': Int64Index([ 1908,  2074,  2124,  3691,  3766,  4279,  4888,  5395,  5605,
              5699,  7330,  7662,  7873,  8246, 10438, 12099],
            dtype='int64'),
 'Blackburn Rovers': Int64Index([ 1667,  1809,  2217,  2454,  2650,  3522,  4034,  4070,  4125,
              4538,  4740,  5019,  7593,  8378,  8422, 10529, 10685, 11727,
             11742, 11853, 11966],
            dtype='int64'),
 'Blackpool': Int64Index([ 3536,  3677,  3686,  3987,  4024,  4118,  4639,  6093,  6108,
              6171,  6529,  6802,  6993,  7031,  7447,  7947,  7982,  8397,
              8730,  9491,  9991, 10531, 11307, 11350, 11596, 12533, 12823,
             12867],
            dtype='int64'),
 'Boavista FC': Int64Index([1327, 2073, 2694, 3009, 3055, 3106, 3479, 5232, 5360, 5484, 6792,
             6880, 11377],
            dtype='int64'),
 'Boca Juniors': Int64Index([374, 482, 517, 554, 579, 590, 1002, 1091, 1206, 1803, 8367, 9099,
             9787],
            dtype='int64'),
 'Bohemian FC': Int64Index([ 6257,  9723, 10084, 10126, 10545, 10579, 10779, 10903, 11234,
             11542, 11813, 11819, 11996, 12082, 12111, 12125, 12204, 12445,
             12476, 12501, 12618, 12619, 12734, 12799, 12841],
            dtype='int64'),
 'Bologna': Int64Index([588, 607, 627, 721, 1023, 1066, 1285, 1600, 1661, 2666, 9533], dtype='int64'),
 'Bolton Wanderers': Int64Index([ 1763,  1782,  1903,  1911,  2570,  2700,  2911,  3042,  3196,
              3201,  3213,  3530,  3916,  4448,  4967,  5561, 10404, 10590,
             10612, 11928, 12170],
            dtype='int64'),
 'Borussia Dortmund': Int64Index([   68,   134,   209,   233,   245,   266,   273,   294,   360,
               364,   371,   415,   630,   979,  1127,  4748,  6513,  9484,
             10443, 10853, 10995],
            dtype='int64'),
 'Borussia Mönchengladbach': Int64Index([  179,   247,   249,   265,   283,   378,   426,   552,   566,
               616,   637,  2142,  7769,  7869,  7902,  8076,  8262,  8431,
              9744, 10136],
            dtype='int64'),
 'Botafogo': Int64Index([906, 1405, 1430, 1525, 1670, 2350, 2377, 3212, 4213, 4305], dtype='int64'),
 'Bournemouth': Int64Index([  846,  1142,  1256,  8512,  8880,  9292,  9314, 10066, 10163,
             10248, 10643, 10915, 10916, 11006],
            dtype='int64'),
 'Boyacá Chicó FC': Int64Index([ 2264,  4437,  5013,  5255,  5739,  6295,  6831,  7016,  7040,
              7086,  7549,  8207,  8660,  8733,  9452, 10618, 11046, 11405,
             11441, 11465, 11768, 11999, 12002, 12338, 12495, 12588],
            dtype='int64'),
 'Bradford City': Int64Index([ 2205,  3555,  3665,  3981,  4381,  4398,  5740,  5780,  5996,
              6022,  6274,  6516,  6590,  7240,  7704,  7760,  8142,  8222,
              8665,  9460, 10197, 10957, 10958, 11001, 12029, 12195, 12362],
            dtype='int64'),
 'Bray Wanderers': Int64Index([10670, 11060, 11070, 11083, 11106, 11383, 11537, 11651, 11674,
             11814, 11826, 12046, 12251, 12402, 12410, 12591, 12668, 12705,
             12712, 12753, 12801, 12817, 12871],
            dtype='int64'),
 'Brentford': Int64Index([ 1068,  1114,  3065,  3402,  5028,  6010,  6974,  9006,  9975,
             10881, 11171, 11244, 11251, 11305, 11481],
            dtype='int64'),
 'Brescia': Int64Index([ 985, 1596, 2267, 2379, 2425, 3554, 3896, 4145, 4226, 4388, 4399,
             4822, 5401, 5555, 5784, 7709, 7717, 8066, 9141, 9236, 9505, 9546,
             9658],

In [9]:
grouped_df = df.groupby(['Club']).sum()
display(grouped_df)

,Unnamed: 0,Age,Value,Wage,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
Club,,,,,,,,,,,,,,,,,,,,,
SSV Jahn Regensburg,129124,609,15195000,90000,1104,944,1283,1362,944,1196,...,1042,1332,1205,1146,1088,405,406,368,409,424
1. FC Heidenheim 1846,117834,473,18290000,76000,961,860,955,1136,846,1040,...,923,1093,888,952,890,335,317,287,335,306
1. FC Kaiserslautern,167351,544,11195000,33000,1106,918,1133,1272,899,1131,...,1030,1174,938,989,996,392,373,348,368,356
1. FC Köln,54865,225,46810000,92000,444,357,434,567,320,486,...,431,515,453,458,452,272,251,276,252,268
1. FC Magdeburg,116731,515,57525000,84000,948,903,1044,1157,769,1024,...,938,1057,933,930,892,367,373,354,361,394
1. FC Nürnberg,75281,291,28540000,93000,646,627,637,785,561,772,...,579,704,530,581,552,197,194,191,205,185
1. FC Union Berlin,61586,271,9485000,94000,572,448,595,652,417,568,...,497,623,612,626,609,160,167,162,162,145
1. FSV Mainz 05,59103,238,41755000,125000,574,483,625,681,476,683,...,569,620,506,532,516,165,163,140,149,170
AC Ajaccio,118215,507,24000000,42000,958,853,1059,1125,798,1056,...,973,1106,852,944,854,226,251,223,221,260
AC Horsens,210346,625,8650000,55000,1141,1111,1307,1355,1069,1258,...,1025,1330,1180,1118,1082,420,421,420,392,410
AD Alcorcón,89198,506,36875000,70000,1000,856,1073,1107,820,1057,...,972,1121,1000,940,924,238,272,254,236,242
ADO Den Haag,114251,450,14680000,67000,972,792,869,1076,815,1060,...,858,1105,771,846,827,358,361,362,365,379
AEK Athens,43824,266,39550000,11000,521,469,560,643,450,574,...,478,677,535,470,466,232,226,227,232,238
AFC Wimbledon,224698,614,9635000,51000,1164,1041,1323,1371,981,1264,...,1136,1346,1117,1184,1101,422,393,428,437,425
AIK,141183,488,9435000,46000,862,773,965,1041,748,952,...,819,1092,902,862,828,361,354,316,345,326
AJ Auxerre,107765,419,12795000,34000,830,645,941,955,640,875,...,785,984,776,816,796,294,275,285,310,288
AS Béziers,200547,648,9120000,31000,1156,1037,1209,1364,928,1310,...,1148,1320,1070,1082,1065,434,408,425,412,407
AS Monaco,51239,425,162775000,770000,926,840,1000,1158,826,1047,...,885,1199,903,949,905,351,379,351,375,385
AS Nancy Lorraine,153129,627,39770000,53000,1208,1070,1302,1382,982,1330,...,1209,1406,1085,1114,1084,383,365,384,372,381
AS Saint-Étienne,71720,365,59315000,213000,736,684,754,877,627,798,...,736,897,581,608,596,343,331,333,327,342
AZ Alkmaar,35600,226,24550000,60000,473,405,485,606,417,514,...,489,600,486,517,505,215,208,211,208,234
Aalborg BK,186206,508,13090000,59000,994,928,1092,1158,787,1128,...,941,1217,1027,1028,999,333,324,315,329,357
Aarhus GF,194960,592,10920000,72000,1214,1105,1145,1324,1012,1295,...,1083,1360,1106,1024,992,422,422,407,419,412
Aberdeen,131153,427,8355000,49000,850,733,924,1002,711,953,...,770,979,771,806,765,277,312,311,283,296
Accrington Stanley,234511,695,15690000,67000,1231,1131,1404,1465,1124,1385,...,1231,1503,1279,1195,1183,437,450,414,464,397
Adelaide United,192929,578,10300000,33000,1072,1030,1078,1312,891,1246,...,1081,1374,860,990,1002,401,389,403,383,407
Ajax,26041,275,152250000,158000,844,723,848,940,696,932,...,710,929,750,814,756,150,130,139,155,129
Akhisar Belediyespor,55701,408,19140000,94000,728,596,658,822,553,774,...,660,772,689,704,695,338,314,319,326,318
Al Ahli,157761,555,26965000,232000,1041,894,1033,1146,803,1118,...,983,1187,916,968,920,395,387,358,392,396
Al Batin,260133,695,7635000,85000,1111,1048,1284,1383,961,1261,...,1201,1409,1086,1141,1092,491,461,494,495,483
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vitesse,80523,318,28240000,158000,745,673,636,860,601,863,...,611,905,652,603,574,203,204,210,205,195
Vitória,35545,360,12375000,70000,600,578,670,709,608,637,...,644,752,528,573,568,238,208,214,240,260
Vitória Guimarães,14870,176,35475000,55000,406,367,346,454,344,464,...,408,449,313,317,285,141,126,137,134,128
Vitória de Setúbal,58615,346,23750000,36000,595,626,776,765,646,732,...,716,768,590,625,591,258,249,268,264,250
Vålerenga Fotball,179424,532,9765000,33000,1058,913,1181,1288,942,1221,...,981,1256,1013,1123,1064,339,351,360,348,345
Vélez Sarsfield,141043,412,10805000,47000,855,782,881,990,743,1023,...,865,923,779,764,779,288,272,274,292,270
Waasland-Beveren,159163,512,13125000,54000,1089,911,1248,1320,954,1201,...,1083,1304,1048,1113,1079,322,330,334,344,343
Walsall,175266,603,13210000,58000,1191,1103,1322,1379,1011,1371,...,1146,1471,1182,1203,1125,371,372,367,369,355
Waterford FC,263053,597,13210000,27000,1105,997,1142,1298,1005,1238,...,1119,1292,1012,1129,1113,347,352,367,338,368
Watford,58021,291,42425000,317000,569,559,654,693,553,668,...,634,732,561,569,536,202,192,170,178,196
Wellington Phoenix,154492,484,8485000,24000,858,795,955,1014,723,955,...,864,1071,892,909,886,331,304,315,306,289
West Bromwich Albion,81670,476,50395000,306000,983,899,1062,1142,821,1074,...,1015,1192,940,934,892,308,294,301,288,309
West Ham United,78156,603,175020000,1221000,1356,1186,1403,1552,1180,1538,...,1294,1627,1216,1285,1235,382,374,353,345,365
Western Sydney Wanderers,183508,489,7185000,40000,917,867,964,1107,778,1026,...,917,1135,897,858,808,357,343,346,332,378
Wigan Athletic,86566,303,14885000,127000,552,440,538,637,436,572,...,525,620,490,543,515,280,272,269,288,273
Willem II,140913,545,26870000,114000,1136,964,1141,1373,941,1258,...,1086,1416,1102,1166,1112,456,439,449,434,471
Wisła Kraków,171752,567,8965000,43000,1104,974,1128,1264,933,1167,...,1076,1319,936,1034,1020,417,400,390,364,415
Wisła Płock,205965,572,15035000,38000,1043,921,1087,1257,911,1191,...,1052,1258,920,1007,1001,432,420,432,405,431
Wolfsberger AC,194345,584,9015000,65000,1031,865,1175,1239,841,1209,...,998,1259,1119,1111,1107,412,430,403,393,406
Wolverhampton Wanderers,129112,442,74740000,411000,1027,893,994,1171,853,1137,...,938,1198,974,1007,961,318,297,301,308,299
Wycombe Wanderers,160575,664,18030000,56000,1204,1095,1226,1353,997,1297,...,1165,1364,1119,1127,1085,374,343,361,352,392
Yeni Malatyaspor,143864,555,22470000,95000,1036,920,1103,1222,855,1163,...,1052,1162,958,966,918,427,444,447,404,419
Yeovil Town,258720,679,9115000,52000,1204,1184,1357,1396,1005,1422,...,1233,1468,1111,1139,1095,434,454,429,442,424
Yokohama F. Marinos,215364,642,10235000,39000,1148,1028,1124,1342,944,1214,...,1050,1313,1093,1043,944,463,445,430,467,466
Zagłębie Lubin,185069,642,9620000,42000,1157,1058,1222,1355,967,1294,...,1186,1399,1005,1084,1095,432,405,431,425,427
Zagłębie Sosnowiec,220803,656,6815000,27000,1161,1007,1152,1357,979,1252,...,1113,1371,1219,1187,1156,427,391,417,391,413
Çaykur Rizespor,119137,557,27515000,118000,1110,921,1137,1290,888,1233,...,1063,1200,1050,1155,1143,375,394,387,388,389
Örebro SK,224465,622,8465000,36000,1114,974,1149,1311,965,1270,...,1066,1393,1112,1045,1008,412,406,386,428,407
Östersunds FK,136103,478,11030000,39000,944,805,856,1109,801,1066,...,847,1132,920,842,816,342,357,369,337,363
Śląsk Wrocław,172358,628,9170000,50000,1058,1054,1289,1313,988,1238,...,1150,1314,1047,1161,1129,408,403,367,394,403

In [10]:
grouped_df.loc['Ajax']

Unnamed: 0             26041
Age                      275
Value              152250000
Wage                  158000
Crossing                 844
Finishing                723
HeadingAccuracy          848
ShortPassing             940
Volleys                  696
Dribbling                932
Curve                    779
FKAccuracy               680
LongPassing              878
BallControl              951
Acceleration             944
SprintSpeed              969
Agility                  969
Reactions                924
Balance                  918
ShotPower                876
Jumping                  915
Stamina                  974
Strength                 896
LongShots                720
Aggression               847
Interceptions            801
Positioning              813
Vision                   881
Penalties                710
Composure                929
Marking                  750
StandingTackle           814
SlidingTackle            756
GKDiving                 150
GKHandling               130
GKKicking                139
GKPositioning            155
GKReflexes               129
Name: Ajax, dtype: int64

In [12]:
grouped_df.iloc[1]

Unnamed: 0           117834
Age                     473
Value              18290000
Wage                  76000
Crossing                961
Finishing               860
HeadingAccuracy         955
ShortPassing           1136
Volleys                 846
Dribbling              1040
Curve                   904
FKAccuracy              823
LongPassing             940
BallControl            1099
Acceleration           1285
SprintSpeed            1309
Agility                1273
Reactions              1188
Balance                1203
ShotPower              1103
Jumping                1237
Stamina                1208
Strength               1280
LongShots               872
Aggression             1023
Interceptions           919
Positioning             896
Vision                  958
Penalties               923
Composure              1093
Marking                 888
StandingTackle          952
SlidingTackle           890
GKDiving                335
GKHandling              317
GKKicking               287
GKPositioning           335
GKReflexes              306
Name: 1. FC Heidenheim 1846, dtype: int64

In [13]:
grouped_df.loc['Ajax']['Wage']

158000

In [15]:
df.groupby(['Club']).sum().loc['Ajax']['Wage']

158000

In [16]:
grouped_df = df.groupby(['Club'])['Wage'].sum()
display(grouped_df)

Club
 SSV Jahn Regensburg          90000
1. FC Heidenheim 1846         76000
1. FC Kaiserslautern          33000
1. FC Köln                    92000
1. FC Magdeburg               84000
1. FC Nürnberg                93000
1. FC Union Berlin            94000
1. FSV Mainz 05              125000
AC Ajaccio                    42000
AC Horsens                    55000
AD Alcorcón                   70000
ADO Den Haag                  67000
AEK Athens                    11000
AFC Wimbledon                 51000
AIK                           46000
AJ Auxerre                    34000
AS Béziers                    31000
AS Monaco                    770000
AS Nancy Lorraine             53000
AS Saint-Étienne             213000
AZ Alkmaar                    60000
Aalborg BK                    59000
Aarhus GF                     72000
Aberdeen                      49000
Accrington Stanley            67000
Adelaide United               33000
Ajax                         158000
Akhisar Belediyespor          94000
Al Ahli                      232000
Al Batin                      85000
                             ...
Vitesse                      158000
Vitória                       70000
Vitória Guimarães             55000
Vitória de Setúbal            36000
Vålerenga Fotball             33000
Vélez Sarsfield               47000
Waasland-Beveren              54000
Walsall                       58000
Waterford FC                  27000
Watford                      317000
Wellington Phoenix            24000
West Bromwich Albion         306000
West Ham United             1221000
Western Sydney Wanderers      40000
Wigan Athletic               127000
Willem II                    114000
Wisła Kraków                  43000
Wisła Płock                   38000
Wolfsberger AC                65000
Wolverhampton Wanderers      411000
Wycombe Wanderers             56000
Yeni Malatyaspor              95000
Yeovil Town                   52000
Yokohama F. Marinos           39000
Zagłębie Lubin                42000
Zagłębie Sosnowiec            27000
Çaykur Rizespor              118000
Örebro SK                     36000
Östersunds FK                 39000
Śląsk Wrocław                 50000
Name: Wage, Length: 650, dtype: int64

In [18]:
grouped_df = df.groupby(['Club'])['Wage'].sum().sort_values(ascending=False)
#display(grouped_df)
grouped_df.head(5)

Club
Real Madrid          4138000
FC Barcelona         3967000
Manchester City      3097000
Manchester United    2357000
Juventus             2335000
Name: Wage, dtype: int64

In [19]:
grouped_df = df.groupby(['Position'])['Wage'].sum().sort_values(ascending=False)
grouped_df
#grouped_df.head(20)

Position
ST     11873000
GK      8784000
CB      7476000
CM      6194000
LB      6096000
CAM     5500000
LM      5440000
RM      5098000
RB      5034000
CDM     4921000
RCB     4711000
LCB     3989000
RW      3276000
RCM     3241000
LCM     3145000
LW      2945000
LS      1866000
RDM     1557000
RS      1537000
LDM     1516000
RF       714000
LF       601000
RWB      420000
LAM      366000
LWB      347000
CF       248000
RAM       59000
Name: Wage, dtype: int64

In [20]:
df.groupby(['Nationality'])[['Wage','Age','ShotPower']].mean()

                              Wage        Age  ShotPower
Nationality
Afghanistan            1250.000000  22.500000  53.750000
Albania                5931.034483  23.689655  54.551724
Algeria               15810.810811  27.027027  56.567568
Andorra                1000.000000  28.000000  58.000000
Angola                 7100.000000  24.700000  63.700000
Antigua & Barbuda      1333.333333  23.000000  50.333333
Argentina             10264.808362  25.890244  54.033101
Armenia                8500.000000  26.750000  66.375000
Australia              2223.300971  24.174757  47.325243
Austria                5441.666667  24.341667  50.650000
Azerbaijan             2200.000000  26.000000  69.800000
Barbados               3666.666667  27.666667  52.333333
Belarus                4500.000000  27.500000  43.000000
Belgium               20024.390244  24.030488  56.390244
Belize                 1000.000000  25.000000  66.000000
Benin                  2125.000000  25.000000  52.750000
Bermuda                3000.000000  27.000000  58.000000
Bolivia                3200.000000  24.600000  51.200000
Bosnia Herzegovina    14756.756757  26.027027  55.945946
Botswana               1000.000000  20.000000  55.000000
Brazil                17371.158392  27.898345  58.203310
Bulgaria               1750.000000  25.625000  52.625000
Burkina Faso          11083.333333  24.916667  60.083333
Burundi                3500.000000  23.000000  60.000000
Cameroon               9818.181818  23.836364  58.818182
Canada                 1923.076923  24.346154  53.576923
Cape Verde             4375.000000  27.500000  66.500000
Central African Rep.   3000.000000  25.000000  48.000000
Chile                  4429.054054  24.709459  51.858108
China PR               2810.888252  26.068768  45.839542
...                            ...        ...        ...
Senegal               14166.666667  24.743590  58.423077
Serbia                12000.000000  25.917808  57.328767
Sierra Leone           2500.000000  23.250000  55.000000
Slovakia              10702.702703  26.324324  45.648649
Slovenia              11969.696970  26.272727  55.000000
South Africa           2081.081081  26.297297  52.081081
South Sudan            2000.000000  25.000000  60.000000
Spain                 14774.962742  24.965723  55.535022
St Kitts Nevis         2000.000000  26.500000  47.000000
St Lucia               1000.000000  24.000000  50.000000
Sudan                  5333.333333  26.333333  56.666667
Suriname               2333.333333  24.333333  65.666667
Sweden                 2489.028213  24.608150  50.786834
Switzerland            6923.076923  24.288462  51.378205
Syria                 10500.000000  24.500000  60.000000
Tanzania               7000.000000  22.000000  68.333333
Thailand               2400.000000  25.000000  57.200000
Togo                   7400.000000  26.600000  66.400000
Trinidad & Tobago      9666.666667  33.000000  60.000000
Tunisia                5235.294118  26.117647  57.352941
Turkey                 5902.325581  23.962791  51.339535
Uganda                 1400.000000  22.600000  54.800000
Ukraine                4971.428571  24.314286  53.171429
United States          2830.258303  25.014760  48.863469
Uruguay               17590.361446  26.771084  56.192771
Uzbekistan             9000.000000  29.500000  71.500000
Venezuela              6611.111111  23.638889  57.222222
Wales                  9529.411765  24.754902  48.558824
Zambia                 2833.333333  21.833333  66.833333
Zimbabwe               5000.000000  26.555556  62.888889

[156 rows x 3 columns]

In [21]:
df.groupby(['Nationality'])[['Wage','Age','ShotPower']].mean().sort_values(['Wage'],ascending=False).head(10)

                            Wage        Age  ShotPower
Nationality
Dominican Republic  71000.000000  23.000000  75.500000
Egypt               35545.454545  25.818182  59.363636
Gabon               28900.000000  26.400000  56.900000
Croatia             26722.222222  24.819444  54.305556
Equatorial Guinea   25666.666667  28.000000  55.333333
Belgium             20024.390244  24.030488  56.390244
Ecuador             18333.333333  24.619048  60.666667
Uruguay             17590.361446  26.771084  56.192771
Brazil              17371.158392  27.898345  58.203310
Algeria             15810.810811  27.027027  56.567568

In [23]:
df[df['Nationality'] == 'Dominican Republic'][['Name','Club','Wage','Age','ShotPower']]

            Name         Club    Wage  Age  ShotPower
291      Mariano  Real Madrid  140000   24         85
6279  L. Quezada   Córdoba CF    2000   22         66

In [25]:
df.groupby(['Position'])[['Wage','Value']].mean().sort_values(['Value'],ascending=False).head(10)

                   Wage         Value
Position
LF         75125.000000  2.736250e+07
RF        119000.000000  2.636583e+07
LAM        61000.000000  1.324583e+07
RAM        11800.000000  8.345000e+06
LS         15421.487603  5.848430e+06
LCM        13497.854077  4.318090e+06
RCM        13504.166667  4.217604e+06
RS         13482.456140  3.645833e+06
LW         12169.421488  3.603099e+06
RW         13822.784810  3.495738e+06

In [26]:
df.groupby(['Nationality'])[['Club','Name']].nunique()

                      Club  Name
Nationality
Afghanistan              4     4
Albania                 26    29
Algeria                 33    37
Andorra                  1     1
Angola                   9    10
Antigua & Barbuda        3     3
Argentina              133   554
Armenia                  8     8
Australia               51   205
Austria                 47   240
Azerbaijan               5     5
Barbados                 3     3
Belarus                  2     2
Belgium                 68   164
Belize                   1     1
Benin                    8     8
Bermuda                  1     1
Bolivia                  5     5
Bosnia Herzegovina      35    37
Botswana                 1     1
Brazil                 173   408
Bulgaria                 8     8
Burkina Faso            12    12
Burundi                  2     2
Cameroon                49    55
Canada                  29    52
Cape Verde               7     8
Central African Rep.     1     1
Chile                   39   289
China PR                19   343
...                    ...   ...
Senegal                 61    77
Serbia                  62    71
Sierra Leone             4     4
Slovakia                32    37
Slovenia                31    33
South Africa             8    37
South Sudan              1     1
Spain                  117   650
St Kitts Nevis           2     2
St Lucia                 1     1
Sudan                    3     3
Suriname                 3     3
Sweden                  62   312
Switzerland             43   154
Syria                    4     4
Tanzania                 2     3
Thailand                 5     5
Togo                     5     5
Trinidad & Tobago        3     3
Tunisia                 16    17
Turkey                  47   212
Uganda                   5     5
Ukraine                 19    35
United States           67   270
Uruguay                 67    83
Uzbekistan               2     2
Venezuela               34    36
Wales                   56   101
Zambia                   5     6
Zimbabwe                 8     9

[156 rows x 2 columns]

In [29]:
df.groupby(['Club'])['Name'].count()

Club
 SSV Jahn Regensburg        24
1. FC Heidenheim 1846       20
1. FC Kaiserslautern        23
1. FC Köln                  10
1. FC Magdeburg             21
1. FC Nürnberg              13
1. FC Union Berlin          11
1. FSV Mainz 05             11
AC Ajaccio                  19
AC Horsens                  25
AD Alcorcón                 19
ADO Den Haag                19
AEK Athens                  11
AFC Wimbledon               26
AIK                         19
AJ Auxerre                  17
AS Béziers                  25
AS Monaco                   18
AS Nancy Lorraine           25
AS Saint-Étienne            15
AZ Alkmaar                  10
Aalborg BK                  22
Aarhus GF                   25
Aberdeen                    18
Accrington Stanley          28
Adelaide United             24
Ajax                        13
Akhisar Belediyespor        14
Al Ahli                     22
Al Batin                    28
                            ..
Vitesse                     14
Vitória                     12
Vitória Guimarães            7
Vitória de Setúbal          14
Vålerenga Fotball           23
Vélez Sarsfield             18
Waasland-Beveren            23
Walsall                     25
Waterford FC                25
Watford                     12
Wellington Phoenix          19
West Bromwich Albion        19
West Ham United             24
Western Sydney Wanderers    21
Wigan Athletic              12
Willem II                   24
Wisła Kraków                23
Wisła Płock                 24
Wolfsberger AC              24
Wolverhampton Wanderers     20
Wycombe Wanderers           24
Yeni Malatyaspor            22
Yeovil Town                 28
Yokohama F. Marinos         26
Zagłębie Lubin              25
Zagłębie Sosnowiec          25
Çaykur Rizespor             22
Örebro SK                   26
Östersunds FK               20
Śląsk Wrocław               24
Name: Name, Length: 650, dtype: int64

In [30]:
df.groupby(['Club'])['Dribbling'].median()

Club
 SSV Jahn Regensburg        57.5
1. FC Heidenheim 1846       59.5
1. FC Kaiserslautern        54.0
1. FC Köln                  60.5
1. FC Magdeburg             53.0
1. FC Nürnberg              57.0
1. FC Union Berlin          61.0
1. FSV Mainz 05             71.0
AC Ajaccio                  61.0
AC Horsens                  58.0
AD Alcorcón                 62.0
ADO Den Haag                62.0
AEK Athens                  63.0
AFC Wimbledon               55.5
AIK                         60.0
AJ Auxerre                  58.0
AS Béziers                  58.0
AS Monaco                   61.5
AS Nancy Lorraine           57.0
AS Saint-Étienne            60.0
AZ Alkmaar                  63.5
Aalborg BK                  56.0
Aarhus GF                   60.0
Aberdeen                    57.5
Accrington Stanley          55.0
Adelaide United             57.0
Ajax                        71.0
Akhisar Belediyespor        65.5
Al Ahli                     54.0
Al Batin                    50.0
                            ...
Vitesse                     62.5
Vitória                     56.0
Vitória Guimarães           75.0
Vitória de Setúbal          57.5
Vålerenga Fotball           57.0
Vélez Sarsfield             63.5
Waasland-Beveren            60.0
Walsall                     58.0
Waterford FC                56.0
Watford                     64.5
Wellington Phoenix          54.0
West Bromwich Albion        63.0
West Ham United             70.5
Western Sydney Wanderers    56.0
Wigan Athletic              53.0
Willem II                   60.5
Wisła Kraków                58.0
Wisła Płock                 56.5
Wolfsberger AC              54.5
Wolverhampton Wanderers     60.0
Wycombe Wanderers           59.5
Yeni Malatyaspor            64.5
Yeovil Town                 58.0
Yokohama F. Marinos         51.5
Zagłębie Lubin              56.0
Zagłębie Sosnowiec          58.0
Çaykur Rizespor             62.0
Örebro SK                   55.0
Östersunds FK               61.5
Śląsk Wrocław               54.5
Name: Dribbling, Length: 650, dtype: float64

In [31]:
df.groupby(['Club'])['Strength'].max()

Club
 SSV Jahn Regensburg        92
1. FC Heidenheim 1846       86
1. FC Kaiserslautern        85
1. FC Köln                  76
1. FC Magdeburg             86
1. FC Nürnberg              84
1. FC Union Berlin          87
1. FSV Mainz 05             85
AC Ajaccio                  82
AC Horsens                  87
AD Alcorcón                 88
ADO Den Haag                90
AEK Athens                  87
AFC Wimbledon               91
AIK                         92
AJ Auxerre                  90
AS Béziers                  84
AS Monaco                   90
AS Nancy Lorraine           83
AS Saint-Étienne            78
AZ Alkmaar                  77
Aalborg BK                  80
Aarhus GF                   82
Aberdeen                    84
Accrington Stanley          86
Adelaide United             89
Ajax                        87
Akhisar Belediyespor        81
Al Ahli                     83
Al Batin                    90
                            ..
Vitesse                     80
Vitória                     90
Vitória Guimarães           74
Vitória de Setúbal          85
Vålerenga Fotball           94
Vélez Sarsfield             82
Waasland-Beveren            89
Walsall                     83
Waterford FC                90
Watford                     93
Wellington Phoenix          83
West Bromwich Albion        84
West Ham United             92
Western Sydney Wanderers    86
Wigan Athletic              75
Willem II                   82
Wisła Kraków                87
Wisła Płock                 83
Wolfsberger AC              80
Wolverhampton Wanderers     93
Wycombe Wanderers           97
Yeni Malatyaspor            82
Yeovil Town                 91
Yokohama F. Marinos         78
Zagłębie Lubin              90
Zagłębie Sosnowiec          84
Çaykur Rizespor             81
Örebro SK                   85
Östersunds FK               88
Śląsk Wrocław               85
Name: Strength, Length: 650, dtype: int64

In [32]:
df.groupby(['Club'])['Balance'].min()

Club
 SSV Jahn Regensburg        29
1. FC Heidenheim 1846       22
1. FC Kaiserslautern        29
1. FC Köln                  31
1. FC Magdeburg             19
1. FC Nürnberg              44
1. FC Union Berlin          24
1. FSV Mainz 05             39
AC Ajaccio                  54
AC Horsens                  35
AD Alcorcón                 38
ADO Den Haag                28
AEK Athens                  29
AFC Wimbledon               25
AIK                         26
AJ Auxerre                  30
AS Béziers                  35
AS Monaco                   35
AS Nancy Lorraine           34
AS Saint-Étienne            22
AZ Alkmaar                  38
Aalborg BK                  33
Aarhus GF                   27
Aberdeen                    44
Accrington Stanley          38
Adelaide United             25
Ajax                        59
Akhisar Belediyespor        35
Al Ahli                     38
Al Batin                    34
                            ..
Vitesse                     36
Vitória                     31
Vitória Guimarães           25
Vitória de Setúbal          29
Vålerenga Fotball           42
Vélez Sarsfield             44
Waasland-Beveren            29
Walsall                     31
Waterford FC                31
Watford                     45
Wellington Phoenix          43
West Bromwich Albion        48
West Ham United             40
Western Sydney Wanderers    29
Wigan Athletic              30
Willem II                   28
Wisła Kraków                28
Wisła Płock                 25
Wolfsberger AC              34
Wolverhampton Wanderers     32
Wycombe Wanderers           24
Yeni Malatyaspor            21
Yeovil Town                 31
Yokohama F. Marinos         32
Zagłębie Lubin              30
Zagłębie Sosnowiec          28
Çaykur Rizespor             39
Örebro SK                   34
Östersunds FK               32
Śląsk Wrocław               31
Name: Balance, Length: 650, dtype: int64

In [33]:
df.groupby(['Club'])['Wage'].mean()

Club
 SSV Jahn Regensburg         3750.000000
1. FC Heidenheim 1846        3800.000000
1. FC Kaiserslautern         1434.782609
1. FC Köln                   9200.000000
1. FC Magdeburg              4000.000000
1. FC Nürnberg               7153.846154
1. FC Union Berlin           8545.454545
1. FSV Mainz 05             11363.636364
AC Ajaccio                   2210.526316
AC Horsens                   2200.000000
AD Alcorcón                  3684.210526
ADO Den Haag                 3526.315789
AEK Athens                   1000.000000
AFC Wimbledon                1961.538462
AIK                          2421.052632
AJ Auxerre                   2000.000000
AS Béziers                   1240.000000
AS Monaco                   42777.777778
AS Nancy Lorraine            2120.000000
AS Saint-Étienne            14200.000000
AZ Alkmaar                   6000.000000
Aalborg BK                   2681.818182
Aarhus GF                    2880.000000
Aberdeen                     2722.222222
Accrington Stanley           2392.857143
Adelaide United              1375.000000
Ajax                        12153.846154
Akhisar Belediyespor         6714.285714
Al Ahli                     10545.454545
Al Batin                     3035.714286
                                ...
Vitesse                     11285.714286
Vitória                      5833.333333
Vitória Guimarães            7857.142857
Vitória de Setúbal           2571.428571
Vålerenga Fotball            1434.782609
Vélez Sarsfield              2611.111111
Waasland-Beveren             2347.826087
Walsall                      2320.000000
Waterford FC                 1080.000000
Watford                     26416.666667
Wellington Phoenix           1263.157895
West Bromwich Albion        16105.263158
West Ham United             50875.000000
Western Sydney Wanderers     1904.761905
Wigan Athletic              10583.333333
Willem II                    4750.000000
Wisła Kraków                 1869.565217
Wisła Płock                  1583.333333
Wolfsberger AC               2708.333333
Wolverhampton Wanderers     20550.000000
Wycombe Wanderers            2333.333333
Yeni Malatyaspor             4318.181818
Yeovil Town                  1857.142857
Yokohama F. Marinos          1500.000000
Zagłębie Lubin               1680.000000
Zagłębie Sosnowiec           1080.000000
Çaykur Rizespor              5363.636364
Örebro SK                    1384.615385
Östersunds FK                1950.000000
Śląsk Wrocław                2083.333333
Name: Wage, Length: 650, dtype: float64

In [37]:
df_grouped = df.groupby(['Club'])['Wage'].agg(['mean', 'median'])
#df[df['Nationality'] == 'Argentina']
len(df_grouped[df_grouped['mean'] == df_grouped['median']])

52

In [39]:
df_grouped[df_grouped['mean'] == df_grouped['median']].sort_values(['mean'],ascending=False).head(10)

                      mean  median
Club
Cruzeiro           13000.0   13000
Göztepe SK          7000.0    7000
Brøndby IF          6000.0    6000
Sunderland          4000.0    4000
CD Feirense         4000.0    4000
1. FC Magdeburg     4000.0    4000
Northampton Town    2500.0    2500
Stade Brestois 29   2000.0    2000
Jeonnam Dragons     2000.0    2000
Pohang Steelers     2000.0    2000

In [41]:
df.groupby(['Club'])['Wage'].sum()['Chelsea']

2035000

In [50]:
df[df['Age'] == 20].groupby(['Nationality'])['Wage'].max().loc['Argentina']

54000

In [51]:
df[df['Age'] == 30].groupby(['Nationality'])['Wage'].max().loc['Argentina']

300000

In [52]:
df[df['Age'] == 30].groupby(['Nationality'])['Wage'].min().loc['Argentina']

1000

In [60]:
df[df['Nationality'] == 'Argentina'].groupby(['Club'])['Strength', 'Balance'].max().loc['FC Barcelona']

Strength    59
Balance     95
Name: FC Barcelona, dtype: int64

In [63]:
df.loc[df['Club'].isin(['FC Barcelona','Real Madrid','Juventus','Manchester United'])]

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF,84,95,...,75,96,33,28,26,6,11,15,14,8
1,1,Cristiano Ronaldo,33,Portugal,Juventus,77000000,405000,ST,84,94,...,85,95,28,31,23,7,11,15,14,11
3,3,De Gea,27,Spain,Manchester United,72000000,260000,GK,17,13,...,40,68,15,21,13,90,85,87,88,94
6,6,L. Modrić,32,Croatia,Real Madrid,67000000,420000,RCM,86,72,...,82,84,60,76,73,13,9,7,14,9
7,7,L. Suárez,31,Uruguay,FC Barcelona,80000000,455000,RS,77,93,...,85,85,62,45,38,27,25,31,33,37
8,8,Sergio Ramos,32,Spain,Real Madrid,51000000,380000,RCB,66,60,...,75,82,87,92,91,11,8,9,7,11
11,11,T. Kroos,28,Germany,Real Madrid,76500000,355000,LCM,88,76,...,73,85,72,79,69,10,11,13,7,10
15,15,P. Dybala,24,Argentina,Juventus,89000000,205000,LF,82,84,...,86,84,23,20,20,5,4,4,5,8
18,18,M. ter Stegen,26,Germany,FC Barcelona,58000000,240000,GK,15,14,...,25,69,25,13,10,87,85,88,85,90
19,19,T. Courtois,26,Belgium,Real Madrid,53500000,240000,GK,14,14,...,27,66,20,18,16,85,91,72,86,88
20,20,Sergio Busquets,29,Spain,FC Barcelona,51500000,315000,CDM,62,67,...,60,90,90,86,80,5,8,13,9,13
24,24,G. Chiellini,33,Italy,Juventus,27000000,215000,LCB,58,33,...,50,84,93,93,90,3,3,2,4,3
27,27,Casemiro,26,Brazil,Real Madrid,59500000,285000,CDM,52,59,...,66,84,88,90,87,13,14,16,12,12
30,30,Isco,26,Spain,Real Madrid,73500000,315000,LW,75,79,...,76,86,60,64,51,10,8,12,15,6
32,32,Coutinho,26,Brazil,FC Barcelona,69500000,340000,LW,79,79,...,70,85,55,54,47,12,7,9,14,6
35,35,Marcelo,30,Brazil,Real Madrid,43000000,285000,LB,90,70,...,59,86,71,85,86,12,5,5,5,9
36,36,G. Bale,28,Wales,Real Madrid,60000000,355000,ST,87,86,...,76,86,54,55,52,15,15,11,5,6
42,42,S. Umtiti,24,France,FC Barcelona,57000000,205000,CB,69,51,...,61,82,90,89,86,15,10,14,12,15
45,45,P. Pogba,25,France,Manchester United,64000000,210000,RDM,80,73,...,81,87,66,70,68,5,6,2,4,3
46,46,K. Navas,31,Costa Rica,Real Madrid,30500000,195000,GK,11,15,...,25,67,28,14,14,90,81,75,82,90
47,47,R. Lukaku,25,Belgium,Manchester United,62500000,230000,ST,78,87,...,78,83,30,30,30,8,15,14,7,10
49,49,Jordi Alba,29,Spain,FC Barcelona,38000000,250000,LB,87,73,...,59,79,72,84,85,13,15,13,6,13
53,53,I. Rakitić,30,Croatia,FC Barcelona,46500000,260000,RCM,84,83,...,82,81,72,74,70,14,11,12,5,9
54,54,Piqué,31,Spain,FC Barcelona,34000000,240000,RCB,57,64,...,69,86,91,86,84,10,11,14,15,8
62,62,R. Varane,25,France,Real Madrid,50000000,210000,RCB,36,40,...,43,82,87,88,87,11,11,9,5,14
64,64,Alex Sandro,27,Brazil,Juventus,36500000,160000,LB,84,55,...,60,82,81,84,84,7,7,9,12,5
65,65,Douglas Costa,27,Brazil,Juventus,46500000,175000,LM,84,67,...,77,84,45,38,34,13,15,9,12,5
70,70,L. Bonucci,31,Italy,Juventus,30000000,160000,RCB,44,48,...,70,86,90,86,80,2,2,3,2,4
72,72,M. Pjanić,28,Bosnia Herzegovina,Juventus,44000000,180000,CDM,80,60,...,79,86,75,74,70,7,7,13,7,8
73,73,M. Benatia,31,Morocco,Juventus,30000000,160000,CB,45,47,...,41,82,89,87,85,7,4,8,7,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,239,Dani Ceballos,21,Spain,Real Madrid,25000000,120000,LCM,74,68,...,55,80,62,75,74,12,15,16,7,13
263,263,C. Smalling,28,England,Manchester United,16000000,130000,RCB,52,54,...,52,67,81,82,80,10,15,16,15,15
276,276,A. Valencia,32,Ecuador,Manchester United,10000000,120000,RM,79,60,...,55,82,77,82,79,16,11,10,7,7
291,291,Mariano,24,Dominican Republic,Real Madrid,20000000,140000,ST,50,81,...,75,68,41,40,34,12,14,6,8,15
335,336,S. Romero,31,Argentina,Manchester United,9000000,91000,GK,11,14,...,16,62,14,11,15,78,76,81,77,82
362,365,Marcos Llorente,23,Spain,Real Madrid,16000000,110000,CDM,56,39,...,53,76,76,79,72,13,6,6,11,15
394,397,M. Rojo,28,Argentina,Manchester United,10000000,115000,CB,74,50,...,64,73,76,81,79,7,8,12,15,10
408,411,P. Jones,26,England,Manchester United,12000000,110000,CB,60,44,...,55,68,76,81,82,10,8,6,16,11
442,446,A. Young,32,England,Manchester United,7000000,110000,LB,84,64,...,60,74,75,76,74,16,10,15,16,15
491,495,Andreas Pereira,22,Brazil,Manchester United,14000000,91000,CM,78,74,...,70,74,67,65,63,15,14,7,10,7
605,613,T. Vermaelen,32,Belgium,FC Barcelona,5000000,110000,CB,63,52,...,62,72,72,79,80,9,10,7,11,15
612,620,L. Spinazzola,25,Italy,Juventus,11000000,80000,LM,76,60,...,59,74,77,76,76,11,13,12,15,14
731,741,M. Darmian,28,Italy,Manchester United,6000000,88000,LB,69,55,...,45,76,77,79,78,6,7,7,12,7
1464,1515,Aleñá,20,Spain,FC Barcelona,6000000,58000,CM,66,66,...,73,70,70,62,48,12,9,10,8,12
5135,5293,Fidalgo,21,Spain,Real Madrid,875000,20000,CM,61,49,...,49,68,46,51,47,10,9,10,11,9
5314,5475,E. Hamilton,19,Scotland,Manchester United,1000000,11000,CM,57,58,...,51,54,57,54,53,7,11,5,9,11
5377,5539,Chumi,19,Spain,FC Barcelona,1000000,11000,CB,38,30,...,50,62,70,65,63,7,14,9,11,14
5613,5777,Jorge Cuenca,18,Spain,FC Barcelona,850000,11000,CB,40,27,...,44,57,62,66,63,10,12,5,14,12
5907,6074,R. Poole,20,Wales,Manchester United,675000,13000,CB,34,28,...,37,55,61,64,61,16,15,13,7,12
5989,6156,Sergio López,19,Spain,Real Madrid,875000,9000,RB,63,52,...,43,62,59,61,62,12,12,11,7,13
6124,6293,Guillem Jaime,19,Spain,FC Barcelona,975000,13000,RW,63,54,...,49,66,52,55,56,9,11,12,10,6
6150,6320,Fran García,18,Spain,Real Madrid,550000,9000,LB,65,42,...,39,60,60,58,59,9,6,12,9,11
6244,6415,R. Williams,19,England,Manchester United,2400000,8000,CB,32,27,...,49,51,63,68,66,7,5,6,6,9
6694,6869,Manu Hernando,19,Spain,Real Madrid,700000,9000,CB,44,32,...,42,47,70,65,67,11,12,13,12,5
7312,7493,Ezkieta,21,Spain,FC Barcelona,525000,10000,GK,16,12,...,24,33,13,17,15,65,58,59,59,64
7314,7495,Dani Gómez,19,Spain,Real Madrid,800000,12000,ST,32,67,...,57,44,41,12,15,7,10,13,8,14
7354,7536,J. Bohui,19,England,Manchester United,700000,10000,ST,45,62,...,64,57,20,16,16,9,7,10,13,11
8436,8628,L. Zidane,20,France,Real Madrid,350000,9000,GK,12,8,...,19,36,13,11,13,65,60,61,62,61
8644,8837,P. Beruatto,19,Italy,Juventus,575000,5000,LB,50,10,...,43,56,64,66,68,14,5,12,10,12
9028,9226,Iñaki Peña,19,Spain,FC Barcelona,450000,4000,GK,10,6,...,17,38,9,10,11,63,57,64,57,62

In [65]:
pivot = df.loc[df['Club'].isin(['FC Barcelona','Real Madrid','Juventus','Manchester United'])]\
.pivot_table(values=['Wage'], index=['Nationality'], columns=['Club'], aggfunc='sum', margins=True)
display(pivot)

                           Wage                                           \
Club               FC Barcelona   Juventus Manchester United Real Madrid
Nationality
Argentina              565000.0   205000.0          206000.0         NaN
Belgium                110000.0        NaN          230000.0    240000.0
Bosnia Herzegovina          NaN   180000.0               NaN         NaN
Brazil                 465000.0   335000.0           91000.0    570000.0
Chile                  205000.0        NaN          215000.0         NaN
Costa Rica                  NaN        NaN               NaN    195000.0
Croatia                260000.0   160000.0               NaN    420000.0
Dominican Republic          NaN        NaN               NaN    140000.0
Ecuador                     NaN        NaN          120000.0         NaN
England                     NaN        NaN          478000.0         NaN
France                 495000.0   145000.0          375000.0    459000.0
Germany                240000.0   160000.0               NaN    355000.0
Italy                       NaN   460000.0           88000.0         NaN
Ivory Coast                 NaN        NaN          105000.0         NaN
Morocco                     NaN   160000.0               NaN         NaN
Netherlands            135000.0        NaN               NaN         NaN
Poland                      NaN   125000.0               NaN         NaN
Portugal               125000.0   405000.0               NaN         NaN
Scotland                    NaN        NaN           11000.0         NaN
Serbia                      NaN        NaN          165000.0         NaN
Spain                  912000.0        NaN          260000.0   1404000.0
Uruguay                455000.0        NaN               NaN         NaN
Wales                       NaN        NaN           13000.0    355000.0
All                   3967000.0  2335000.0         2357000.0   4138000.0


Club                     All
Nationality
Argentina             976000
Belgium               580000
Bosnia Herzegovina    180000
Brazil               1461000
Chile                 420000
Costa Rica            195000
Croatia               840000
Dominican Republic    140000
Ecuador               120000
England               478000
France               1474000
Germany               755000
Italy                 548000
Ivory Coast           105000
Morocco               160000
Netherlands           135000
Poland                125000
Portugal              530000
Scotland               11000
Serbia                165000
Spain                2576000
Uruguay               455000
Wales                 368000
All                 12797000

In [66]:
pivot.loc['Belgium']

      Club
Wage  FC Barcelona         110000.0
      Juventus                  NaN
      Manchester United    230000.0
      Real Madrid          240000.0
      All                  580000.0
Name: Belgium, dtype: float64

In [67]:
pivot = df.loc[df['Club'].isin(['FC Barcelona','Real Madrid','Juventus','Manchester United'])]\
.pivot_table(values=['Wage'], index=['Nationality'], columns=['Club'], aggfunc='sum', margins=True, fill_value=0)
pivot

                           Wage                                         \
Club               FC Barcelona Juventus Manchester United Real Madrid
Nationality
Argentina                565000   205000            206000           0
Belgium                  110000        0            230000      240000
Bosnia Herzegovina            0   180000                 0           0
Brazil                   465000   335000             91000      570000
Chile                    205000        0            215000           0
Costa Rica                    0        0                 0      195000
Croatia                  260000   160000                 0      420000
Dominican Republic            0        0                 0      140000
Ecuador                       0        0            120000           0
England                       0        0            478000           0
France                   495000   145000            375000      459000
Germany                  240000   160000                 0      355000
Italy                         0   460000             88000           0
Ivory Coast                   0        0            105000           0
Morocco                       0   160000                 0           0
Netherlands              135000        0                 0           0
Poland                        0   125000                 0           0
Portugal                 125000   405000                 0           0
Scotland                      0        0             11000           0
Serbia                        0        0            165000           0
Spain                    912000        0            260000     1404000
Uruguay                  455000        0                 0           0
Wales                         0        0             13000      355000
All                     3967000  2335000           2357000     4138000


Club                     All
Nationality
Argentina             976000
Belgium               580000
Bosnia Herzegovina    180000
Brazil               1461000
Chile                 420000
Costa Rica            195000
Croatia               840000
Dominican Republic    140000
Ecuador               120000
England               478000
France               1474000
Germany               755000
Italy                 548000
Ivory Coast           105000
Morocco               160000
Netherlands           135000
Poland                125000
Portugal              530000
Scotland               11000
Serbia                165000
Spain                2576000
Uruguay               455000
Wales                 368000
All                 12797000

In [68]:
pivot = df.loc[df['Club'].isin(['FC Barcelona','Real Madrid','Juventus','Manchester United'])] \
.pivot_table(values=['Name'], index=['Nationality'], columns=['Club'], aggfunc='count', fill_value=0)
display(pivot)

                           Name
Club               FC Barcelona Juventus Manchester United Real Madrid
Nationality
Argentina                     1        1                 2           0
Belgium                       1        0                 1           1
Bosnia Herzegovina            0        1                 0           0
Brazil                        2        2                 1           2
Chile                         1        0                 1           0
Costa Rica                    0        0                 0           1
Croatia                       1        1                 0           1
Dominican Republic            0        0                 0           1
Ecuador                       0        0                 1           0
England                       0        0                 6           0
France                        3        1                 2           3
Germany                       1        1                 0           1
Italy                         0        4                 1           0
Ivory Coast                   0        0                 1           0
Morocco                       0        1                 0           0
Netherlands                   1        0                 0           0
Poland                        0        1                 0           0
Portugal                      1        1                 0           0
Scotland                      0        0                 1           0
Serbia                        0        0                 1           0
Spain                         9        0                 1          11
Uruguay                       1        0                 0           0
Wales                         0        0                 1           1

In [71]:
pivot.loc['Argentina']['Name']['Manchester United']

2

In [ ]:
pivot = df.loc[df['Club'].isin(['FC Barcelona','Real Madrid','Juventus','Manchester United'])] \
.pivot_table(values=['Name'], index=['Nationality'], columns=['Club'], aggfunc='count', fill_value=0)
display(pivot)

In [112]:
pivot = df.loc[df['Position'] != 'CM'] \
.pivot_table(values=['Name'], index=['Club'], columns=['Position'], aggfunc='count', margins=False, fill_value=0)
pivot

                         Name                                  ...             \
Position                  CAM CB CDM CF GK LAM LB LCB LCM LDM  ... RB RCB RCM
Club                                                           ...
 SSV Jahn Regensburg        0  5   1  0  3   0  2   0   0   1  ...  2   1   0
1. FC Heidenheim 1846       1  3   0  0  2   0  2   1   0   0  ...  2   1   0
1. FC Kaiserslautern        0  3   3  0  3   0  2   1   0   0  ...  2   0   0
1. FC Köln                  0  1   1  0  3   0  0   0   0   0  ...  1   0   0
1. FC Magdeburg             0  4   0  1  3   0  1   1   1   0  ...  0   1   1
1. FC Nürnberg              1  1   2  0  1   0  1   0   0   0  ...  1   0   0
1. FC Union Berlin          1  2   2  0  1   0  2   1   0   0  ...  1   0   0
1. FSV Mainz 05             0  2   0  0  1   0  1   0   1   0  ...  1   0   0
AC Ajaccio                  3  1   0  0  1   0  3   1   0   1  ...  1   1   0
AC Horsens                  0  3   1  0  3   0  3   1   1   0  ...  1   1   1
AD Alcorcón                 0  3   1  0  1   0  2   1   0   1  ...  2   1   0
ADO Den Haag                3  1   1  0  3   0  1   0   1   0  ...  2   1   0
AEK Athens                  3  1   0  0  2   0  2   1   0   0  ...  0   0   0
AFC Wimbledon               1  4   0  0  3   0  2   1   1   0  ...  2   1   1
AIK                         0  4   0  0  3   0  0   1   0   0  ...  0   0   0
AJ Auxerre                  3  2   1  0  2   0  2   0   0   0  ...  3   1   0
AS Béziers                  2  2   2  0  3   0  2   1   0   1  ...  1   1   0
AS Monaco                   1  2   1  0  3   0  1   1   0   0  ...  2   1   0
AS Nancy Lorraine           1  3   3  0  2   0  3   0   0   1  ...  2   0   0
AS Saint-Étienne            1  1   1  0  3   0  2   0   0   0  ...  1   0   0
AZ Alkmaar                  1  2   0  0  2   0  1   0   0   0  ...  1   0   0
Aalborg BK                  0  3   0  0  2   0  3   1   1   0  ...  2   0   1
Aarhus GF                   1  2   2  0  3   0  2   1   1   0  ...  1   0   0
Aberdeen                    0  3   3  0  2   0  0   0   0   0  ...  1   1   0
Accrington Stanley          0  3   1  0  3   0  2   1   1   0  ...  3   1   1
Adelaide United             4  1   1  0  3   0  1   1   1   0  ...  2   1   1
Ajax                        0  1   0  0  0   0  3   0   0   1  ...  1   1   0
Akhisar Belediyespor        2  0   1  0  3   0  1   0   0   0  ...  2   1   0
Al Ahli                     0  2   5  0  3   0  3   0   1   0  ...  2   1   0
Al Batin                    0  3   2  0  4   0  2   1   0   1  ...  2   1   0
...                       ... ..  .. .. ..  .. ..  ..  ..  ..  ... ..  ..  ..
Vitesse                     1  1   2  0  1   0  3   0   0   0  ...  1   0   0
Vitória                     3  1   1  0  2   0  1   1   0   0  ...  1   0   0
Vitória Guimarães           0  0   0  0  1   0  0   0   1   0  ...  1   0   0
Vitória de Setúbal          1  3   0  0  2   0  1   0   0   1  ...  0   0   0
Vålerenga Fotball           1  2   1  0  2   0  2   1   0   0  ...  2   1   0
Vélez Sarsfield             0  2   1  0  2   0  2   0   0   0  ...  2   1   0
Waasland-Beveren            4  3   1  0  2   0  1   1   1   0  ...  1   1   1
Walsall                     0  3   0  0  2   0  1   1   0   0  ...  3   1   1
Waterford FC                4  2   2  0  2   0  2   1   1   0  ...  1   1   1
Watford                     1  2   0  0  1   0  0   0   0   0  ...  2   1   0
Wellington Phoenix          3  3   1  0  2   0  1   1   1   0  ...  0   1   1
West Bromwich Albion        1  3   1  0  2   0  1   0   0   0  ...  2   1   0
West Ham United             1  2   2  0  2   0  2   1   1   0  ...  2   0   0
Western Sydney Wanderers    1  3   1  0  3   0  1   1   1   0  ...  0   1   1
Wigan Athletic              0  2   1  0  3   0  1   0   0   0  ...  1   0   0
Willem II                   2  2   1  0  4   0  2   1   0   0  ...  2   1   1
Wisła Kraków                1  3   1  0  3   0  2   1   0   1  ...  3   1   0
Wisła Płock                 1  2   1  0  4   0  3   1   0   0  ...  1   1   1
Wolfsberger AC              1  2   0  0  3   0  2   1   1   0  ...  3   1   1
Wolverhampton Wanderers     0  4   0  0  2   0  0   1   0   0  ...  0   0   1
Wycombe Wanderers           0  3   0  0  2   0  1   1   1   0  ...  2   1   1
Yeni Malatyaspor            2  2   3  0  4   0  1   0   0   1  ...  2   0   0
Yeovil Town                 0  3   0  0  3   0  2   1   1   0  ...  2   1   1
Yokohama F. Marinos         3  4   2  0  4   0  1   0   1   0  ...  2   0   1
Zagłębie Lubin              0  0   2  0  3   0  2   1   0   2  ...  2   1   0
Zagłębie Sosnowiec          3  2   2  0  3   0  3   1   0   1  ...  1   1   0
Çaykur Rizespor             1  2   5  0  3   0  2   1   0   1  ...  3   0   0
Örebro SK                   0  4   0  0  3   0  0   1   1   0  ...  0   1   1
Östersunds FK               1  1   0  1  3   0  2   1   1   0  ...  1   1   0
Śląsk Wrocław               0  1   3  0  3   0  2   1   0   1  ...  2   1   0


Position                 RDM RF RM RS RW RWB ST
Club
 SSV Jahn Regensburg       1  0  0  0  0   0  3
1. FC Heidenheim 1846      0  0  3  0  0   0  2
1. FC Kaiserslautern       1  0  2  1  0   0  1
1. FC Köln                 0  0  1  0  0   0  0
1. FC Magdeburg            0  0  3  1  2   0  1
1. FC Nürnberg             0  0  2  0  0   0  3
1. FC Union Berlin         0  0  0  0  0   0  0
1. FSV Mainz 05            0  0  0  1  0   0  1
AC Ajaccio                 1  0  1  0  0   0  3
AC Horsens                 0  0  2  1  0   0  2
AD Alcorcón                0  0  1  0  0   0  4
ADO Den Haag               0  0  0  0  2   0  0
AEK Athens                 0  0  1  0  0   0  0
AFC Wimbledon              0  0  2  1  0   0  3
AIK                        0  0  0  0  0   2  3
AJ Auxerre                 0  0  0  0  0   0  2
AS Béziers                 1  0  1  0  0   0  3
AS Monaco                  0  0  1  1  0   0  2
AS Nancy Lorraine          1  0  1  0  1   0  5
AS Saint-Étienne           0  0  2  0  0   0  2
AZ Alkmaar                 0  0  0  0  0   0  0
Aalborg BK                 0  0  1  0  0   0  4
Aarhus GF                  0  0  1  0  0   0  4
Aberdeen                   1  0  1  0  0   0  3
Accrington Stanley         0  0  2  1  0   0  4
Adelaide United            0  0  0  0  2   0  3
Ajax                       0  0  0  0  1   0  1
Akhisar Belediyespor       1  0  1  0  0   0  0
Al Ahli                    0  0  1  1  0   0  1
Al Batin                   1  0  2  1  0   0  4
...                       .. .. .. .. ..  .. ..
Vitesse                    0  0  0  0  4   0  1
Vitória                    1  0  0  0  0   0  1
Vitória Guimarães          0  0  1  0  0   0  1
Vitória de Setúbal         0  0  0  0  1   0  3
Vålerenga Fotball          1  0  1  0  1   0  1
Vélez Sarsfield            0  0  0  0  2   0  4
Waasland-Beveren           0  0  2  1  0   1  2
Walsall                    0  0  2  1  0   0  3
Waterford FC               0  0  1  1  0   0  0
Watford                    0  0  1  0  0   0  4
Wellington Phoenix         0  0  0  0  0   1  2
West Bromwich Albion       0  0  1  1  0   0  2
West Ham United            0  0  3  0  0   0  2
Western Sydney Wanderers   0  0  0  0  2   0  3
Wigan Athletic             0  0  1  0  0   0  0
Willem II                  0  0  0  0  1   0  1
Wisła Kraków               0  0  1  0  0   0  3
Wisła Płock                0  0  1  0  0   0  3
Wolfsberger AC             0  0  0  0  0   0  2
Wolverhampton Wanderers    0  0  0  1  1   3  2
Wycombe Wanderers          0  0  1  1  1   0  1
Yeni Malatyaspor           0  0  1  0  0   0  2
Yeovil Town                0  0  5  1  0   0  4
Yokohama F. Marinos        0  0  1  0  1   0  3
Zagłębie Lubin             1  0  4  0  0   0  4
Zagłębie Sosnowiec         1  0  2  0  0   0  1
Çaykur Rizespor            1  0  1  0  0   0  1
Örebro SK                  0  0  0  0  2   2  5
Östersunds FK              0  0  1  0  1   0  1
Śląsk Wrocław              1  0  2  1  0   0  2

[650 rows x 26 columns]

In [103]:
pivot = df.pivot_table(values=['Name'], index=['Position'], columns=['Club'], aggfunc='count', margins=False, fill_value=0)
pivot

                         Name                                             \
Club      SSV Jahn Regensburg 1. FC Heidenheim 1846 1. FC Kaiserslautern
Position
CAM                         0                     1                    0
CB                          5                     3                    3
CDM                         1                     0                    3
CF                          0                     0                    0
CM                          2                     1                    0
GK                          3                     2                    3
LAM                         0                     0                    0
LB                          2                     2                    2
LCB                         0                     1                    1
LCM                         0                     0                    0
LDM                         1                     0                    0
LF                          0                     0                    0
LM                          2                     2                    2
LS                          0                     0                    1
LW                          0                     0                    1
LWB                         0                     0                    0
RAM                         1                     0                    0
RB                          2                     2                    2
RCB                         1                     1                    0
RCM                         0                     0                    0
RDM                         1                     0                    1
RF                          0                     0                    0
RM                          0                     3                    2
RS                          0                     0                    1
RW                          0                     0                    0
RWB                         0                     0                    0
ST                          3                     2                    1

                                                                       \
Club     1. FC Köln 1. FC Magdeburg 1. FC Nürnberg 1. FC Union Berlin
Position
CAM               0               0              1                  1
CB                1               4              1                  2
CDM               1               0              2                  2
CF                0               1              0                  0
CM                2               0              1                  1
GK                3               3              1                  1
LAM               0               0              0                  0
LB                0               1              1                  2
LCB               0               1              0                  1
LCM               0               1              0                  0
LDM               0               0              0                  0
LF                0               0              0                  0
LM                0               0              0                  0
LS                0               1              0                  0
LW                0               0              0                  0
LWB               1               0              0                  0
RAM               0               0              0                  0
RB                1               0              1                  1
RCB               0               1              0                  0
RCM               0               1              0                  0
RDM               0               0              0                  0
RF                0               0              0                  0
RM                1               3              2                  0
RS                0               1              0                  0
RW                0               2              0                  0
RWB               0               0              0                  0
ST                0               1              3                  0

                                                ...                    \
Club     1. FSV Mainz 05 AC Ajaccio AC Horsens  ... Wycombe Wanderers
Position                                        ...
CAM                    0          3          0  ...                 0
CB                     2          1          3  ...                 3
CDM                    0          0          1  ...                 0
CF                     0          0          0  ...                 0
CM                     1          1          2  ...                 4
GK                     1          1          3  ...                 2
LAM                    0          0          0  ...                 0
LB                     1          3          3  ...                 1
LCB                    0          1          1  ...                 1
LCM                    1          0          1  ...                 1
LDM                    0          1          0  ...                 0
LF                     0          0          0  ...                 0
LM                     0          1          2  ...                 0
LS                     0          0          1  ...                 1
LW                     2          0          0  ...                 3
LWB                    0          0          0  ...                 0
RAM                    0          0          0  ...                 0
RB                     1          1          1  ...                 2
RCB                    0          1          1  ...                 1
RCM                    0          0          1  ...                 1
RDM                    0          1          0  ...                 0
RF                     0          0          0  ...                 0
RM                     0          1          2  ...                 1
RS                     1          0          1  ...                 1
RW                     0          0          0  ...                 1
RWB                    0          0          0  ...                 0
ST                     1          3          2  ...                 1

                                                                          \
Club     Yeni Malatyaspor Yeovil Town Yokohama F. Marinos Zagłębie Lubin
Position
CAM                     2           0                   3              0
CB                      2           3                   4              0
CDM                     3           0                   2              2
CF                      0           0                   0              0
CM                      2           1                   1              1
GK                      4           3                   4              3
LAM                     0           0                   0              0
LB                      1           2                   1              2
LCB                     0           1                   0              1
LCM                     0           1                   1              0
LDM                     1           0                   0              2
LF                      0           0                   0              0
LM                      2           2                   1              2
LS                      0           1                   0              0
LW                      0           0                   1              0
LWB                     0           0                   0              0
RAM                     0           0                   0              0
RB                      2           2                   2              2
RCB                     0           1                   0              1
RCM                     0           1                   1              0
RDM                     0           0                   0              1
RF                      0           0                   0              0
RM                      1           5                   1              4
RS                      0           1                   0              0
RW                      0           0                   1              0
RWB                     0           0                   0              0
ST                      2           4                   3              4

                                                                     \
Club     Zagłębie Sosnowiec Çaykur Rizespor Örebro SK Östersunds FK
Position
CAM                       3               1         0             1
CB                        2               2         4             1
CDM                       2               5         0             0
CF                        0               0         0             1
CM                        0               0         1             3
GK                        3               3         3             3
LAM                       0               0         0             0
LB                        3               2         0             2
LCB                       1               1         1             1
LCM                       0               0         1             1
LDM                       1               1         0             0
LF                        0               0         0             0
LM                        4               1         0             2
LS                        0               0         0             0
LW                        0               0         3             0
LWB                       0               0         2             0
RAM                       0               0         0             0
RB                        1               3         0             1
RCB                       1               0         1             1
RCM                       0               0         1             0
RDM                       1               1         0             0
RF                        0               0         0             0
RM                        2               1         0             1
RS                        0               0         0             0
RW                        0               0         2             1
RWB                       0               0         2             0
ST                        1               1         5             1


Club     Śląsk Wrocław
Position
CAM                  0
CB                   1
CDM                  3
CF                   0
CM                   1
GK                   3
LAM                  0
LB                   2
LCB                  1
LCM                  0
LDM                  1
LF                   0
LM                   2
LS                   1
LW                   0
LWB                  0
RAM                  0
RB                   2
RCB                  1
RCM                  0
RDM                  1
RF                   0
RM                   2
RS                   1
RW                   0
RWB                  0
ST                   2

[27 rows x 650 columns]

In [115]:
pivot = df.pivot_table(columns='Position', index = 'Club',values = 'Name', aggfunc='count', fill_value=0)
pivot

Position,CAM,CB,CDM,CF,CM,GK,LAM,LB,LCB,LCM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
Club,,,,,,,,,,,,,,,,,,,,,
SSV Jahn Regensburg,0,5,1,0,2,3,0,2,0,0,...,2,1,0,1,0,0,0,0,0,3
1. FC Heidenheim 1846,1,3,0,0,1,2,0,2,1,0,...,2,1,0,0,0,3,0,0,0,2
1. FC Kaiserslautern,0,3,3,0,0,3,0,2,1,0,...,2,0,0,1,0,2,1,0,0,1
1. FC Köln,0,1,1,0,2,3,0,0,0,0,...,1,0,0,0,0,1,0,0,0,0
1. FC Magdeburg,0,4,0,1,0,3,0,1,1,1,...,0,1,1,0,0,3,1,2,0,1
1. FC Nürnberg,1,1,2,0,1,1,0,1,0,0,...,1,0,0,0,0,2,0,0,0,3
1. FC Union Berlin,1,2,2,0,1,1,0,2,1,0,...,1,0,0,0,0,0,0,0,0,0
1. FSV Mainz 05,0,2,0,0,1,1,0,1,0,1,...,1,0,0,0,0,0,1,0,0,1
AC Ajaccio,3,1,0,0,1,1,0,3,1,0,...,1,1,0,1,0,1,0,0,0,3
AC Horsens,0,3,1,0,2,3,0,3,1,1,...,1,1,1,0,0,2,1,0,0,2
AD Alcorcón,0,3,1,0,1,1,0,2,1,0,...,2,1,0,0,0,1,0,0,0,4
ADO Den Haag,3,1,1,0,1,3,0,1,0,1,...,2,1,0,0,0,0,0,2,0,0
AEK Athens,3,1,0,0,0,2,0,2,1,0,...,0,0,0,0,0,1,0,0,0,0
AFC Wimbledon,1,4,0,0,2,3,0,2,1,1,...,2,1,1,0,0,2,1,0,0,3
AIK,0,4,0,0,3,3,0,0,1,0,...,0,0,0,0,0,0,0,0,2,3
AJ Auxerre,3,2,1,0,1,2,0,2,0,0,...,3,1,0,0,0,0,0,0,0,2
AS Béziers,2,2,2,0,3,3,0,2,1,0,...,1,1,0,1,0,1,0,0,0,3
AS Monaco,1,2,1,0,2,3,0,1,1,0,...,2,1,0,0,0,1,1,0,0,2
AS Nancy Lorraine,1,3,3,0,0,2,0,3,0,0,...,2,0,0,1,0,1,0,1,0,5
AS Saint-Étienne,1,1,1,0,1,3,0,2,0,0,...,1,0,0,0,0,2,0,0,0,2
AZ Alkmaar,1,2,0,0,2,2,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
Aalborg BK,0,3,0,0,3,2,0,3,1,1,...,2,0,1,0,0,1,0,0,0,4
Aarhus GF,1,2,2,0,3,3,0,2,1,1,...,1,0,0,0,0,1,0,0,0,4
Aberdeen,0,3,3,0,2,2,0,0,0,0,...,1,1,0,1,0,1,0,0,0,3
Accrington Stanley,0,3,1,0,2,3,0,2,1,1,...,3,1,1,0,0,2,1,0,0,4
Adelaide United,4,1,1,0,1,3,0,1,1,1,...,2,1,1,0,0,0,0,2,0,3
Ajax,0,1,0,0,2,0,0,3,0,0,...,1,1,0,0,0,0,0,1,0,1
Akhisar Belediyespor,2,0,1,0,2,3,0,1,0,0,...,2,1,0,1,0,1,0,0,0,0
Al Ahli,0,2,5,0,0,3,0,3,0,1,...,2,1,0,0,0,1,1,0,0,1
Al Batin,0,3,2,0,2,4,0,2,1,0,...,2,1,0,1,0,2,1,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vitesse,1,1,2,0,0,1,0,3,0,0,...,1,0,0,0,0,0,0,4,0,1
Vitória,3,1,1,0,0,2,0,1,1,0,...,1,0,0,1,0,0,0,0,0,1
Vitória Guimarães,0,0,0,0,1,1,0,0,0,1,...,1,0,0,0,0,1,0,0,0,1
Vitória de Setúbal,1,3,0,0,1,2,0,1,0,0,...,0,0,0,0,0,0,0,1,0,3
Vålerenga Fotball,1,2,1,0,5,2,0,2,1,0,...,2,1,0,1,0,1,0,1,0,1
Vélez Sarsfield,0,2,1,0,0,2,0,2,0,0,...,2,1,0,0,0,0,0,2,0,4
Waasland-Beveren,4,3,1,0,0,2,0,1,1,1,...,1,1,1,0,0,2,1,0,1,2
Walsall,0,3,0,0,4,2,0,1,1,0,...,3,1,1,0,0,2,1,0,0,3
Waterford FC,4,2,2,0,3,2,0,2,1,1,...,1,1,1,0,0,1,1,0,0,0
Watford,1,2,0,0,0,1,0,0,0,0,...,2,1,0,0,0,1,0,0,0,4
Wellington Phoenix,3,3,1,0,0,2,0,1,1,1,...,0,1,1,0,0,0,0,0,1,2
West Bromwich Albion,1,3,1,0,1,2,0,1,0,0,...,2,1,0,0,0,1,1,0,0,2
West Ham United,1,2,2,0,3,2,0,2,1,1,...,2,0,0,0,0,3,0,0,0,2
Western Sydney Wanderers,1,3,1,0,1,3,0,1,1,1,...,0,1,1,0,0,0,0,2,0,3
Wigan Athletic,0,2,1,0,2,3,0,1,0,0,...,1,0,0,0,0,1,0,0,0,0
Willem II,2,2,1,0,3,4,0,2,1,0,...,2,1,1,0,0,0,0,1,0,1
Wisła Kraków,1,3,1,0,1,3,0,2,1,0,...,3,1,0,0,0,1,0,0,0,3
Wisła Płock,1,2,1,0,2,4,0,3,1,0,...,1,1,1,0,0,1,0,0,0,3
Wolfsberger AC,1,2,0,0,4,3,0,2,1,1,...,3,1,1,0,0,0,0,0,0,2
Wolverhampton Wanderers,0,4,0,0,3,2,0,0,1,0,...,0,0,1,0,0,0,1,1,3,2
Wycombe Wanderers,0,3,0,0,4,2,0,1,1,1,...,2,1,1,0,0,1,1,1,0,1
Yeni Malatyaspor,2,2,3,0,2,4,0,1,0,0,...,2,0,0,0,0,1,0,0,0,2
Yeovil Town,0,3,0,0,1,3,0,2,1,1,...,2,1,1,0,0,5,1,0,0,4
Yokohama F. Marinos,3,4,2,0,1,4,0,1,0,1,...,2,0,1,0,0,1,0,1,0,3
Zagłębie Lubin,0,0,2,0,1,3,0,2,1,0,...,2,1,0,1,0,4,0,0,0,4
Zagłębie Sosnowiec,3,2,2,0,0,3,0,3,1,0,...,1,1,0,1,0,2,0,0,0,1
Çaykur Rizespor,1,2,5,0,0,3,0,2,1,0,...,3,0,0,1,0,1,0,0,0,1
Örebro SK,0,4,0,0,1,3,0,0,1,1,...,0,1,1,0,0,0,0,2,2,5
Östersunds FK,1,1,0,1,3,3,0,2,1,1,...,1,1,0,0,0,1,0,1,0,1
Śląsk Wrocław,0,1,3,0,1,3,0,2,1,0,...,2,1,0,1,0,2,1,0,0,2

In [116]:
posCM = pivot['CM'].value_counts()
posCM

1    211
2    149
0    136
3     89
4     39
5     21
6      5
Name: CM, dtype: int64

In [126]:
pivot = df.pivot_table(columns='Nationality', index = 'Club', values = 'Wage', aggfunc='sum', fill_value=0)
pivot1 = pivot['Russia']['AS Monaco']
pivot1
#pivot['Russia'].value_counts()
#pvt = pivot['AS Monaco']
#pvt

61000

In [129]:
pivot = df.pivot_table(columns='Position', index = 'Club', values = 'SprintSpeed', aggfunc='mean', fill_value=0)
pivot

Position,CAM,CB,CDM,CF,CM,GK,LAM,LB,LCB,LCM,...,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
Club,,,,,,,,,,,,,,,,,,,,,
SSV Jahn Regensburg,0.000000,46.600000,82.000000,0.0,61.000000,33.000000,0,76.000000,0.0,0.0,...,68.500000,57.0,0,65.0,0,0.000000,0,0.00,0.0,61.666667
1. FC Heidenheim 1846,68.000000,61.333333,0.000000,0.0,68.000000,41.000000,0,60.000000,55.0,0.0,...,80.500000,59.0,0,0.0,0,78.333333,0,0.00,0.0,69.000000
1. FC Kaiserslautern,0.000000,59.000000,65.666667,0.0,0.000000,42.666667,0,68.000000,45.0,0.0,...,71.500000,0.0,0,55.0,0,82.500000,69,0.00,0.0,79.000000
1. FC Köln,0.000000,60.000000,32.000000,0.0,68.500000,33.000000,0,0.000000,0.0,0.0,...,70.000000,0.0,0,0.0,0,77.000000,0,0.00,0.0,0.000000
1. FC Magdeburg,0.000000,60.000000,0.000000,64.0,0.000000,39.333333,0,69.000000,60.0,66.0,...,0.000000,68.0,71,0.0,0,76.000000,53,80.50,0.0,44.000000
1. FC Nürnberg,66.000000,55.000000,59.000000,0.0,53.000000,40.000000,0,65.000000,0.0,0.0,...,75.000000,0.0,0,0.0,0,83.000000,0,0.00,0.0,65.666667
1. FC Union Berlin,61.000000,59.000000,66.500000,0.0,72.000000,32.000000,0,70.500000,53.0,0.0,...,86.000000,0.0,0,0.0,0,0.000000,0,0.00,0.0,0.000000
1. FSV Mainz 05,0.000000,71.500000,0.000000,0.0,69.000000,40.000000,0,69.000000,0.0,64.0,...,79.000000,0.0,0,0.0,0,0.000000,86,0.00,0.0,69.000000
AC Ajaccio,71.333333,46.000000,0.000000,0.0,77.000000,46.000000,0,67.666667,52.0,0.0,...,67.000000,75.0,0,60.0,0,71.000000,0,0.00,0.0,66.000000
AC Horsens,0.000000,53.333333,56.000000,0.0,62.500000,34.333333,0,66.000000,57.0,76.0,...,78.000000,57.0,63,0.0,0,61.000000,81,0.00,0.0,52.500000
AD Alcorcón,0.000000,56.000000,69.000000,0.0,63.000000,22.000000,0,73.500000,50.0,0.0,...,61.500000,38.0,0,0.0,0,79.000000,0,0.00,0.0,68.250000
ADO Den Haag,56.000000,70.000000,53.000000,0.0,54.000000,33.333333,0,65.000000,0.0,67.0,...,68.500000,31.0,0,0.0,0,0.000000,0,86.00,0.0,0.000000
AEK Athens,71.333333,65.000000,0.000000,0.0,0.000000,33.500000,0,76.500000,52.0,0.0,...,0.000000,0.0,0,0.0,0,72.000000,0,0.00,0.0,0.000000
AFC Wimbledon,67.000000,64.250000,0.000000,0.0,67.000000,40.000000,0,59.500000,51.0,60.0,...,77.000000,69.0,54,0.0,0,77.500000,69,0.00,0.0,59.000000
AIK,0.000000,64.500000,0.000000,0.0,56.000000,29.000000,0,0.000000,62.0,0.0,...,0.000000,0.0,0,0.0,0,0.000000,0,0.00,79.0,73.000000
AJ Auxerre,62.000000,52.500000,67.000000,0.0,61.000000,49.000000,0,68.500000,0.0,0.0,...,70.333333,34.0,0,0.0,0,0.000000,0,0.00,0.0,70.500000
AS Béziers,80.500000,62.500000,67.500000,0.0,69.333333,45.333333,0,81.500000,66.0,0.0,...,74.000000,69.0,0,48.0,0,75.000000,0,0.00,0.0,73.000000
AS Monaco,83.000000,51.000000,62.000000,0.0,64.000000,48.000000,0,64.000000,65.0,0.0,...,79.000000,52.0,0,0.0,0,76.000000,66,0.00,0.0,78.500000
AS Nancy Lorraine,76.000000,61.333333,51.666667,0.0,0.000000,32.500000,0,73.000000,0.0,0.0,...,69.000000,0.0,0,52.0,0,65.000000,0,75.00,0.0,72.400000
AS Saint-Étienne,64.000000,57.000000,61.000000,0.0,62.000000,40.000000,0,73.000000,0.0,0.0,...,61.000000,0.0,0,0.0,0,79.000000,0,0.00,0.0,55.500000
AZ Alkmaar,74.000000,65.000000,0.000000,0.0,65.000000,27.500000,0,72.000000,0.0,0.0,...,79.000000,0.0,0,0.0,0,0.000000,0,0.00,0.0,0.000000
Aalborg BK,0.000000,67.333333,0.000000,0.0,60.666667,50.500000,0,69.333333,55.0,46.0,...,68.500000,0.0,64,0.0,0,73.000000,0,0.00,0.0,64.250000
Aarhus GF,72.000000,56.500000,71.000000,0.0,59.000000,40.333333,0,76.000000,70.0,77.0,...,86.000000,0.0,0,0.0,0,64.000000,0,0.00,0.0,77.000000
Aberdeen,0.000000,49.333333,69.333333,0.0,70.500000,28.500000,0,0.000000,0.0,0.0,...,72.000000,55.0,0,62.0,0,70.000000,0,0.00,0.0,70.333333
Accrington Stanley,0.000000,62.000000,65.000000,0.0,63.000000,34.000000,0,64.500000,37.0,66.0,...,66.666667,74.0,55,0.0,0,77.000000,62,0.00,0.0,76.000000
Adelaide United,60.500000,37.000000,46.000000,0.0,54.000000,36.333333,0,75.000000,56.0,66.0,...,67.500000,54.0,63,0.0,0,0.000000,0,87.00,0.0,66.000000
Ajax,0.000000,76.000000,0.000000,0.0,66.000000,0.000000,0,72.666667,0.0,0.0,...,82.000000,72.0,0,0.0,0,0.000000,0,86.00,0.0,77.000000
Akhisar Belediyespor,67.000000,0.000000,66.000000,0.0,50.500000,50.333333,0,77.000000,0.0,0.0,...,79.000000,53.0,0,56.0,0,55.000000,0,0.00,0.0,0.000000
Al Ahli,0.000000,59.500000,66.400000,0.0,0.000000,46.000000,0,75.333333,0.0,67.0,...,72.500000,50.0,0,0.0,0,87.000000,74,0.00,0.0,63.000000
Al Batin,0.000000,46.000000,64.500000,0.0,66.500000,33.500000,0,68.500000,53.0,0.0,...,63.000000,59.0,0,51.0,0,82.500000,71,0.00,0.0,68.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Vitesse,71.000000,71.000000,65.000000,0.0,0.000000,40.000000,0,64.000000,0.0,0.0,...,76.000000,0.0,0,0.0,0,0.000000,0,77.25,0.0,72.000000
Vitória,70.666667,56.000000,64.000000,0.0,0.000000,42.500000,0,68.000000,61.0,0.0,...,75.000000,0.0,0,72.0,0,0.000000,0,0.00,0.0,91.000000
Vitória Guimarães,0.000000,0.000000,0.000000,0.0,71.000000,28.000000,0,0.000000,0.0,69.0,...,84.000000,0.0,0,0.0,0,70.000000,0,0.00,0.0,77.000000
Vitória de Setúbal,68.000000,53.000000,0.000000,0.0,69.000000,28.500000,0,72.000000,0.0,0.0,...,0.000000,0.0,0,0.0,0,0.000000,0,76.00,0.0,60.666667
Vålerenga Fotball,57.000000,56.000000,50.000000,0.0,67.400000,34.000000,0,73.000000,81.0,0.0,...,71.500000,50.0,0,64.0,0,72.000000,0,69.00,0.0,67.000000
Vélez Sarsfield,0.000000,56.500000,57.000000,0.0,0.000000,32.500000,0,74.500000,0.0,0.0,...,70.500000,62.0,0,0.0,0,0.000000,0,74.00,0.0,59.000000
Waasland-Beveren,64.250000,56.000000,65.000000,0.0,0.000000,41.500000,0,67.000000,32.0,71.0,...,65.000000,45.0,68,0.0,0,74.500000,62,0.00,68.0,75.000000
Walsall,0.000000,66.333333,0.000000,0.0,64.500000,48.500000,0,75.000000,65.0,0.0,...,73.666667,52.0,77,0.0,0,84.500000,67,0.00,0.0,76.666667
Waterford FC,65.750000,57.500000,52.000000,0.0,60.000000,33.500000,0,73.000000,31.0,69.0,...,52.000000,61.0,65,0.0,0,79.000000,80,0.00,0.0,0.000000
Watford,65.000000,51.500000,0.000000,0.0,0.000000,52.000000,0,0.000000,0.0,0.0,...,74.000000,47.0,0,0.0,0,67.000000,0,0.00,0.0,74.750000
Wellington Phoenix,68.666667,52.666667,71.000000,0.0,0.000000,55.000000,0,60.000000,70.0,48.0,...,0.000000,40.0,66,0.0,0,0.000000,0,0.00,73.0,76.000000
West Bromwich Albion,74.000000,60.666667,33.000000,0.0,58.000000,44.000000,0,68.000000,0.0,0.0,...,63.500000,65.0,0,0.0,0,86.000000,77,0.00,0.0,71.000000
West Ham United,78.000000,65.000000,65.000000,0.0,65.000000,40.000000,0,79.000000,68.0,66.0,...,72.500000,0.0,0,0.0,0,80.333333,0,0.00,0.0,59.500000
Western Sydney Wanderers,73.000000,61.666667,65.000000,0.0,66.000000,32.000000,0,80.000000,71.0,76.0,...,0.000000,57.0,73,0.0,0,0.000000,0,88.00,0.0,79.333333
Wigan Athletic,0.000000,57.500000,54.000000,0.0,56.500000,36.000000,0,75.000000,0.0,0.0,...,67.000000,0.0,0,0.0,0,84.000000,0,0.00,0.0,0.000000
Willem II,66.000000,49.000000,67.000000,0.0,60.666667,33.500000,0,67.500000,42.0,0.0,...,83.000000,66.0,72,0.0,0,0.000000,0,77.00,0.0,68.000000
Wisła Kraków,68.000000,63.333333,61.000000,0.0,67.000000,31.666667,0,67.500000,80.0,0.0,...,75.666667,36.0,0,0.0,0,55.000000,0,0.00,0.0,62.333333
Wisła Płock,76.000000,47.000000,66.000000,0.0,69.000000,34.750000,0,70.333333,68.0,0.0,...,70.000000,38.0,65,0.0,0,80.000000,0,0.00,0.0,65.000000
Wolfsberger AC,64.000000,57.500000,0.000000,0.0,60.000000,42.333333,0,71.000000,45.0,72.0,...,67.333333,48.0,77,0.0,0,0.000000,0,0.00,0.0,67.500000
Wolverhampton Wanderers,0.000000,61.750000,0.000000,0.0,64.666667,34.500000,0,0.000000,69.0,0.0,...,0.000000,0.0,59,0.0,0,0.000000,76,86.00,80.0,79.000000
Wycombe Wanderers,0.000000,64.666667,0.000000,0.0,66.500000,44.500000,0,75.000000,45.0,65.0,...,76.500000,65.0,87,0.0,0,87.000000,69,86.00,0.0,82.000000
Yeni Malatyaspor,71.500000,62.000000,65.666667,0.0,64.000000,33.250000,0,75.000000,0.0,0.0,...,70.500000,0.0,0,0.0,0,87.000000,0,0.00,0.0,57.500000
Yeovil Town,0.000000,54.000000,0.000000,0.0,67.000000,37.000000,0,57.000000,44.0,70.0,...,69.500000,59.0,76,0.0,0,78.200000,77,0.00,0.0,74.750000
Yokohama F. Marinos,70.333333,45.250000,61.000000,0.0,67.000000,27.750000,0,70.000000,0.0,72.0,...,68.500000,0.0,72,0.0,0,61.000000,0,65.00,0.0,68.666667
Zagłębie Lubin,0.000000,0.000000,54.000000,0.0,55.000000,44.666667,0,72.000000,33.0,0.0,...,69.500000,50.0,0,61.0,0,75.000000,0,0.00,0.0,65.250000
Zagłębie Sosnowiec,73.000000,46.500000,66.000000,0.0,0.000000,39.000000,0,60.333333,61.0,0.0,...,68.000000,58.0,0,62.0,0,71.000000,0,0.00,0.0,75.000000
Çaykur Rizespor,74.000000,58.000000,62.800000,0.0,0.000000,47.000000,0,75.500000,63.0,0.0,...,68.666667,0.0,0,32.0,0,85.000000,0,0.00,0.0,48.000000
Örebro SK,0.000000,60.750000,0.000000,0.0,63.000000,33.666667,0,0.000000,58.0,44.0,...,0.000000,62.0,66,0.0,0,0.000000,0,77.50,72.0,72.200000
Östersunds FK,67.000000,76.000000,0.000000,77.0,56.333333,32.666667,0,74.500000,53.0,62.0,...,54.000000,73.0,0,0.0,0,85.000000,0,67.00,0.0,52.000000
Śląsk Wrocław,0.000000,62.000000,66.666667,0.0,72.000000,30.666667,0,78.500000,59.0,0.0,...,50.500000,58.0,0,69.0,0,68.000000,81,0.00,0.0,54.000000

In [135]:
pivot.max().sort_values(ascending = False).head(3)

Position
RS    94.0
RM    94.0
LM    94.0
dtype: float64

In [138]:
pivot['ST'].sort_values(ascending = False).head(3)

Club
Vitória      91.0
Sydney FC    88.0
CD Lugo      87.0
Name: ST, dtype: float64